/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Simulate_system_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Printing routine */
#ifdef MATLAB_MEX_FILE
  #define PRINTF mexPrintf
#else
  #define PRINTF printf
#endif

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const int casadi_s1[5] = {1, 1, 0, 1, 0};
static const int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};

void casadi_fill(casadi_real* x, int n, casadi_real alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const int* sp, casadi_real* w) {
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind=sp, *row=sp+ncol+1;
  size_t p_nrow = mxGetM(p), p_ncol = mxGetN(p);
  int is_sparse = mxIsSparse(p);
  mwIndex *Jc, *Ir;
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  const double* p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Dimension mismatch.");
    }
    int r,c,k;
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const int* sp, const casadi_real* x) {
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind = sp, *row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    mxArray*p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    int i;
    mwIndex* j;
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      double* d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  mxArray* p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    double* d = (double*)mxGetData(p);
    int c, k;
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = to_double(*x++);
      }
    }
  }
  return p;
}

#endif

/* Simulate_system:(states[7],controls,params[3])->(xf[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][0] : 0;
  casadi_real a1=4.1666666666666669e-004;
  casadi_real a2=arg[0] ? arg[0][1] : 0;
  casadi_real a3=2.;
  casadi_real a4=1.2500000000000000e-003;
  casadi_real a5=arg[2] ? arg[2][2] : 0;
  casadi_real a6=20000.;
  casadi_real a7=sq(a0);
  a7=(a6*a7);
  casadi_real a8=2000.;
  a7=(a7+a8);
  casadi_real a9=67.;
  a7=(a7/a9);
  a7=(a7*a2);
  casadi_real a10=1200000.;
  casadi_real a11=sq(a0);
  a11=(a10*a11);
  casadi_real a12=1000.;
  a11=(a11+a12);
  a11=(a11*a0);
  a11=(a11/a9);
  a7=(a7+a11);
  a7=(a5-a7);
  a11=9.8100000000000005e+000;
  casadi_real a13=arg[2] ? arg[2][1] : 0;
  a11=(a11*a13);
  a7=(a7+a11);
  a13=10000.;
  casadi_real a14=arg[0] ? arg[0][2] : 0;
  casadi_real a15=(a13*a14);
  a15=(a15/a9);
  a7=(a7-a15);
  a15=(a4*a7);
  a15=(a2+a15);
  casadi_real a16=(a3*a15);
  a16=(a2+a16);
  casadi_real a17=(a4*a2);
  a17=(a0+a17);
  casadi_real a18=sq(a17);
  a18=(a6*a18);
  a18=(a18+a8);
  a18=(a18/a9);
  a18=(a18*a15);
  casadi_real a19=sq(a17);
  a19=(a10*a19);
  a19=(a19+a12);
  a19=(a19*a17);
  a19=(a19/a9);
  a18=(a18+a19);
  a18=(a5-a18);
  a18=(a18+a11);
  a19=fabs(a2);
  a19=(a19*a14);
  casadi_real a20=30.;
  casadi_real a21=3.1830988618379069e-001;
  casadi_real a22=9.8480775301220802e-001;
  casadi_real a23=arg[2] ? arg[2][0] : 0;
  a23=(a9*a23);
  a22=(a22*a23);
  a23=8.5174431145629327e+001;
  a22=(a22+a23);
  a22=atan(a22);
  a21=(a21*a22);
  a22=5.9999999999999998e-001;
  a21=(a21+a22);
  a20=(a20*a21);
  a22=10.;
  a22=(a22*a21);
  a21=5.0000000000000001e-003;
  a23=(a2/a21);
  a23=sq(a23);
  a23=(-a23);
  a23=exp(a23);
  a23=(a22*a23);
  a23=(a20+a23);
  a23=(a23/a13);
  a19=(a19/a23);
  a19=(a2-a19);
  a23=(a4*a19);
  a23=(a14+a23);
  casadi_real a24=(a13*a23);
  a24=(a24/a9);
  a18=(a18-a24);
  a24=(a4*a18);
  a24=(a2+a24);
  casadi_real a25=(a3*a24);
  a16=(a16+a25);
  a25=2.5000000000000001e-003;
  casadi_real a26=(a4*a15);
  a26=(a0+a26);
  casadi_real a27=sq(a26);
  a27=(a6*a27);
  a27=(a27+a8);
  a27=(a27/a9);
  a27=(a27*a24);
  casadi_real a28=sq(a26);
  a28=(a10*a28);
  a28=(a28+a12);
  a28=(a28*a26);
  a28=(a28/a9);
  a27=(a27+a28);
  a27=(a5-a27);
  a27=(a27+a11);
  a28=fabs(a15);
  a28=(a28*a23);
  a23=(a15/a21);
  a23=sq(a23);
  a23=(-a23);
  a23=exp(a23);
  a23=(a22*a23);
  a23=(a20+a23);
  a23=(a23/a13);
  a28=(a28/a23);
  a28=(a15-a28);
  a23=(a4*a28);
  a23=(a14+a23);
  casadi_real a29=(a13*a23);
  a29=(a29/a9);
  a27=(a27-a29);
  a29=(a25*a27);
  a29=(a2+a29);
  a16=(a16+a29);
  a16=(a1*a16);
  a16=(a0+a16);
  a18=(a3*a18);
  a7=(a7+a18);
  a27=(a3*a27);
  a7=(a7+a27);
  a27=(a25*a24);
  a27=(a0+a27);
  a18=sq(a27);
  a18=(a6*a18);
  a18=(a18+a8);
  a18=(a18/a9);
  a18=(a18*a29);
  casadi_real a30=sq(a27);
  a30=(a10*a30);
  a30=(a30+a12);
  a30=(a30*a27);
  a30=(a30/a9);
  a18=(a18+a30);
  a18=(a5-a18);
  a18=(a18+a11);
  a30=fabs(a24);
  a30=(a30*a23);
  a23=(a24/a21);
  a23=sq(a23);
  a23=(-a23);
  a23=exp(a23);
  a23=(a22*a23);
  a23=(a20+a23);
  a23=(a23/a13);
  a30=(a30/a23);
  a30=(a24-a30);
  a23=(a25*a30);
  a23=(a14+a23);
  casadi_real a31=(a13*a23);
  a31=(a31/a9);
  a18=(a18-a31);
  a7=(a7+a18);
  a7=(a1*a7);
  a7=(a2+a7);
  a18=sq(a16);
  a18=(a6*a18);
  a18=(a18+a8);
  a18=(a18/a9);
  a18=(a18*a7);
  a31=sq(a16);
  a31=(a10*a31);
  a31=(a31+a12);
  a31=(a31*a16);
  a31=(a31/a9);
  a18=(a18+a31);
  a18=(a5-a18);
  a18=(a18+a11);
  a28=(a3*a28);
  a19=(a19+a28);
  a30=(a3*a30);
  a19=(a19+a30);
  a30=fabs(a29);
  a30=(a30*a23);
  a23=(a29/a21);
  a23=sq(a23);
  a23=(-a23);
  a23=exp(a23);
  a23=(a22*a23);
  a23=(a20+a23);
  a23=(a23/a13);
  a30=(a30/a23);
  a30=(a29-a30);
  a19=(a19+a30);
  a19=(a1*a19);
  a14=(a14+a19);
  a19=(a13*a14);
  a19=(a19/a9);
  a18=(a18-a19);
  a19=(a4*a18);
  a19=(a7+a19);
  a30=(a3*a19);
  a30=(a7+a30);
  a23=(a4*a7);
  a23=(a16+a23);
  a28=sq(a23);
  a28=(a6*a28);
  a28=(a28+a8);
  a28=(a28/a9);
  a28=(a28*a19);
  a31=sq(a23);
  a31=(a10*a31);
  a31=(a31+a12);
  a31=(a31*a23);
  a31=(a31/a9);
  a28=(a28+a31);
  a28=(a5-a28);
  a28=(a28+a11);
  a31=fabs(a7);
  a31=(a31*a14);
  casadi_real a32=(a7/a21);
  a32=sq(a32);
  a32=(-a32);
  a32=exp(a32);
  a32=(a22*a32);
  a32=(a20+a32);
  a32=(a32/a13);
  a31=(a31/a32);
  a31=(a7-a31);
  a32=(a4*a31);
  a32=(a14+a32);
  casadi_real a33=(a13*a32);
  a33=(a33/a9);
  a28=(a28-a33);
  a33=(a4*a28);
  a33=(a7+a33);
  casadi_real a34=(a3*a33);
  a30=(a30+a34);
  a34=(a4*a19);
  a34=(a16+a34);
  casadi_real a35=sq(a34);
  a35=(a6*a35);
  a35=(a35+a8);
  a35=(a35/a9);
  a35=(a35*a33);
  casadi_real a36=sq(a34);
  a36=(a10*a36);
  a36=(a36+a12);
  a36=(a36*a34);
  a36=(a36/a9);
  a35=(a35+a36);
  a35=(a5-a35);
  a35=(a35+a11);
  a36=fabs(a19);
  a36=(a36*a32);
  a32=(a19/a21);
  a32=sq(a32);
  a32=(-a32);
  a32=exp(a32);
  a32=(a22*a32);
  a32=(a20+a32);
  a32=(a32/a13);
  a36=(a36/a32);
  a36=(a19-a36);
  a32=(a4*a36);
  a32=(a14+a32);
  casadi_real a37=(a13*a32);
  a37=(a37/a9);
  a35=(a35-a37);
  a37=(a25*a35);
  a37=(a7+a37);
  a30=(a30+a37);
  a30=(a1*a30);
  a30=(a16+a30);
  if (res[0]!=0) res[0][0]=a30;
  a28=(a3*a28);
  a18=(a18+a28);
  a35=(a3*a35);
  a18=(a18+a35);
  a35=(a25*a33);
  a35=(a16+a35);
  a28=sq(a35);
  a6=(a6*a28);
  a6=(a6+a8);
  a6=(a6/a9);
  a6=(a6*a37);
  a8=sq(a35);
  a8=(a10*a8);
  a8=(a8+a12);
  a8=(a8*a35);
  a8=(a8/a9);
  a6=(a6+a8);
  a5=(a5-a6);
  a5=(a5+a11);
  a11=fabs(a33);
  a11=(a11*a32);
  a32=(a33/a21);
  a32=sq(a32);
  a32=(-a32);
  a32=exp(a32);
  a32=(a22*a32);
  a32=(a20+a32);
  a32=(a32/a13);
  a11=(a11/a32);
  a11=(a33-a11);
  a32=(a25*a11);
  a32=(a14+a32);
  a6=(a13*a32);
  a6=(a6/a9);
  a5=(a5-a6);
  a18=(a18+a5);
  a18=(a1*a18);
  a18=(a7+a18);
  if (res[0]!=0) res[0][1]=a18;
  a36=(a3*a36);
  a31=(a31+a36);
  a11=(a3*a11);
  a31=(a31+a11);
  a11=fabs(a37);
  a11=(a11*a32);
  a21=(a37/a21);
  a21=sq(a21);
  a21=(-a21);
  a21=exp(a21);
  a22=(a22*a21);
  a20=(a20+a22);
  a20=(a20/a13);
  a11=(a11/a20);
  a11=(a37-a11);
  a31=(a31+a11);
  a31=(a1*a31);
  a14=(a14+a31);
  if (res[0]!=0) res[0][2]=a14;
  a14=arg[0] ? arg[0][3] : 0;
  a31=2400000.;
  a11=sq(a0);
  a11=(a31*a11);
  a11=(a11*a2);
  a0=sq(a0);
  a0=(a10*a0);
  a0=(a0*a2);
  a11=(a11+a0);
  a0=1.6000000000000000e-002;
  a11=(a11/a0);
  a2=arg[1] ? arg[1][0] : 0;
  a20=(a11+a2);
  a13=sq(a17);
  a13=(a31*a13);
  a13=(a13*a15);
  a17=sq(a17);
  a17=(a10*a17);
  a17=(a17*a15);
  a13=(a13+a17);
  a13=(a13/a0);
  a17=(a13+a2);
  a15=(a3*a17);
  a15=(a20+a15);
  a22=sq(a26);
  a22=(a31*a22);
  a22=(a22*a24);
  a26=sq(a26);
  a26=(a10*a26);
  a26=(a26*a24);
  a22=(a22+a26);
  a22=(a22/a0);
  a26=(a22+a2);
  a24=(a3*a26);
  a15=(a15+a24);
  a24=sq(a27);
  a24=(a31*a24);
  a24=(a24*a29);
  a27=sq(a27);
  a27=(a10*a27);
  a27=(a27*a29);
  a24=(a24+a27);
  a24=(a24/a0);
  a27=(a24+a2);
  a15=(a15+a27);
  a15=(a1*a15);
  a15=(a14+a15);
  a27=sq(a16);
  a27=(a31*a27);
  a27=(a27*a7);
  a16=sq(a16);
  a16=(a10*a16);
  a16=(a16*a7);
  a27=(a27+a16);
  a27=(a27/a0);
  a16=(a27+a2);
  a7=sq(a23);
  a7=(a31*a7);
  a7=(a7*a19);
  a23=sq(a23);
  a23=(a10*a23);
  a23=(a23*a19);
  a7=(a7+a23);
  a7=(a7/a0);
  a23=(a7+a2);
  a19=(a3*a23);
  a19=(a16+a19);
  a29=sq(a34);
  a29=(a31*a29);
  a29=(a29*a33);
  a34=sq(a34);
  a34=(a10*a34);
  a34=(a34*a33);
  a29=(a29+a34);
  a29=(a29/a0);
  a34=(a29+a2);
  a33=(a3*a34);
  a19=(a19+a33);
  a33=sq(a35);
  a31=(a31*a33);
  a31=(a31*a37);
  a35=sq(a35);
  a10=(a10*a35);
  a10=(a10*a37);
  a31=(a31+a10);
  a31=(a31/a0);
  a0=(a31+a2);
  a19=(a19+a0);
  a19=(a1*a19);
  a19=(a15+a19);
  if (res[0]!=0) res[0][3]=a19;
  a19=arg[0] ? arg[0][4] : 0;
  a0=(a3*a2);
  a0=(a2+a0);
  a10=(a3*a2);
  a0=(a0+a10);
  a0=(a0+a2);
  a0=(a1*a0);
  a19=(a19+a0);
  a0=(a3*a2);
  a0=(a2+a0);
  a10=(a3*a2);
  a0=(a0+a10);
  a0=(a0+a2);
  a0=(a1*a0);
  a19=(a19+a0);
  if (res[0]!=0) res[0][4]=a19;
  a19=arg[0] ? arg[0][5] : 0;
  a0=-4.7619047619047616e-002;
  a10=(a0*a19);
  a10=(a10+a14);
  a37=(a4*a10);
  a37=(a19+a37);
  a35=(a0*a37);
  a20=(a4*a20);
  a20=(a14+a20);
  a35=(a35+a20);
  a33=(a3*a35);
  a10=(a10+a33);
  a35=(a4*a35);
  a35=(a19+a35);
  a33=(a0*a35);
  a17=(a4*a17);
  a17=(a14+a17);
  a33=(a33+a17);
  a21=(a3*a33);
  a10=(a10+a21);
  a33=(a25*a33);
  a33=(a19+a33);
  a21=(a0*a33);
  a26=(a25*a26);
  a26=(a14+a26);
  a21=(a21+a26);
  a10=(a10+a21);
  a10=(a1*a10);
  a10=(a19+a10);
  a21=(a0*a10);
  a21=(a21+a15);
  a32=(a4*a21);
  a32=(a10+a32);
  a36=(a0*a32);
  a16=(a4*a16);
  a16=(a15+a16);
  a36=(a36+a16);
  a18=(a3*a36);
  a21=(a21+a18);
  a36=(a4*a36);
  a36=(a10+a36);
  a18=(a0*a36);
  a4=(a4*a23);
  a4=(a15+a4);
  a18=(a18+a4);
  a23=(a3*a18);
  a21=(a21+a23);
  a18=(a25*a18);
  a18=(a10+a18);
  a23=(a0*a18);
  a25=(a25*a34);
  a25=(a15+a25);
  a23=(a23+a25);
  a21=(a21+a23);
  a21=(a1*a21);
  a21=(a10+a21);
  if (res[0]!=0) res[0][5]=a21;
  a21=arg[0] ? arg[0][6] : 0;
  a19=(a0*a19);
  a19=(a19+a14);
  a19=(a0*a19);
  a11=(a11+a2);
  a19=(a19+a11);
  a37=(a0*a37);
  a37=(a37+a20);
  a37=(a0*a37);
  a13=(a13+a2);
  a37=(a37+a13);
  a37=(a3*a37);
  a19=(a19+a37);
  a35=(a0*a35);
  a35=(a35+a17);
  a35=(a0*a35);
  a22=(a22+a2);
  a35=(a35+a22);
  a35=(a3*a35);
  a19=(a19+a35);
  a33=(a0*a33);
  a33=(a33+a26);
  a33=(a0*a33);
  a24=(a24+a2);
  a33=(a33+a24);
  a19=(a19+a33);
  a19=(a1*a19);
  a21=(a21+a19);
  a10=(a0*a10);
  a10=(a10+a15);
  a10=(a0*a10);
  a27=(a27+a2);
  a10=(a10+a27);
  a32=(a0*a32);
  a32=(a32+a16);
  a32=(a0*a32);
  a7=(a7+a2);
  a32=(a32+a7);
  a32=(a3*a32);
  a10=(a10+a32);
  a36=(a0*a36);
  a36=(a36+a4);
  a36=(a0*a36);
  a29=(a29+a2);
  a36=(a36+a29);
  a3=(a3*a36);
  a10=(a10+a3);
  a18=(a0*a18);
  a18=(a18+a25);
  a0=(a0*a18);
  a31=(a31+a2);
  a0=(a0+a31);
  a10=(a10+a0);
  a1=(a1*a10);
  a21=(a21+a1);
  if (res[0]!=0) res[0][6]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int Simulate_system(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Simulate_system_incref(void) {
}

CASADI_SYMBOL_EXPORT void Simulate_system_decref(void) {
}

CASADI_SYMBOL_EXPORT int Simulate_system_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int Simulate_system_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* Simulate_system_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Simulate_system_name_out(int i){
  switch (i) {
    case 0: return "xf";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Simulate_system_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Simulate_system_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Simulate_system_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 38;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_Simulate_system(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  int i, j;
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed. Too many output arguments (%d, max 1)", resc);
  int *iw = 0;
  casadi_real w[56];
  const casadi_real* arg[3] = {0};
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+18);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+7, casadi_s1, w+18);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+8, casadi_s2, w+18);
  casadi_real* res[1] = {0};
  --resc;
  res[0] = w+11;
  i = Simulate_system(arg, res, iw, w+18, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[16];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "Simulate_system")==0) {
    return mex_Simulate_system(resc, resv, argc, argv);
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'Simulate_system'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
