/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_src_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f17 CASADI_PREFIX(f17)
#define casadi_f18 CASADI_PREFIX(f18)
#define casadi_f19 CASADI_PREFIX(f19)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f20 CASADI_PREFIX(f20)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const int casadi_s1[5] = {1, 1, 0, 1, 0};
static const int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const int casadi_s3[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const int casadi_s5[3] = {0, 0, 0};
static const int casadi_s6[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const int casadi_s7[21] = {2, 6, 0, 2, 4, 6, 8, 10, 12, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const int casadi_s8[15] = {1, 6, 0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0};
static const int casadi_s9[9] = {0, 6, 0, 0, 0, 0, 0, 0, 0};
static const int casadi_s10[4] = {0, 1, 0, 0};
static const int casadi_s11[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};

/* f_fun:(states[6],controls,params[3])->(xdot[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[2] ? arg[2][2] : 0;
  casadi_real a2=20000.;
  casadi_real a3=arg[0] ? arg[0][0] : 0;
  casadi_real a4=sq(a3);
  a2=(a2*a4);
  a4=2000.;
  a2=(a2+a4);
  a4=67.;
  a2=(a2/a4);
  a2=(a2*a0);
  casadi_real a5=1200000.;
  casadi_real a6=sq(a3);
  a6=(a5*a6);
  casadi_real a7=1000.;
  a6=(a6+a7);
  a6=(a6*a3);
  a6=(a6/a4);
  a2=(a2+a6);
  a1=(a1-a2);
  a2=9.8100000000000005e+000;
  a6=arg[2] ? arg[2][1] : 0;
  a2=(a2*a6);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=2400000.;
  a2=sq(a3);
  a1=(a1*a2);
  a1=(a1*a0);
  a3=sq(a3);
  a5=(a5*a3);
  a5=(a5+a7);
  a5=(a5*a0);
  a1=(a1+a5);
  a5=1.6000000000000000e-002;
  a1=(a1/a5);
  a0=arg[1] ? arg[1][0] : 0;
  a1=(a1+a0);
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a0;
  a0=-4.7619047619047616e-002;
  a1=arg[0] ? arg[0][4] : 0;
  a7=(a0*a1);
  a3=arg[0] ? arg[0][2] : 0;
  a2=(a3/a5);
  a7=(a7+a2);
  if (res[0]!=0) res[0][4]=a7;
  a0=(a0*a1);
  a3=(a3/a5);
  a0=(a0+a3);
  a3=arg[0] ? arg[0][3] : 0;
  a0=(a0+a3);
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int f_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* f_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_out(int i){
  switch (i) {
    case 0: return "xdot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 8;
  return 0;
}

/* vdeFun:(i0[6],i1,i2[3],i3[6x6],i4[6])->(o0[6x6],o1[6]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[3] ? arg[3][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  casadi_real a2=1.4925373134328358e-002;
  casadi_real a3=20000.;
  casadi_real a4=arg[0] ? arg[0][0] : 0;
  casadi_real a5=(a4+a4);
  casadi_real a6=arg[3] ? arg[3][0] : 0;
  casadi_real a7=(a5*a6);
  a7=(a3*a7);
  a7=(a2*a7);
  a7=(a1*a7);
  casadi_real a8=sq(a4);
  a8=(a3*a8);
  casadi_real a9=2000.;
  a8=(a8+a9);
  a9=67.;
  a8=(a8/a9);
  a9=(a8*a0);
  a7=(a7+a9);
  a9=1200000.;
  casadi_real a10=(a4+a4);
  casadi_real a11=(a10*a6);
  a11=(a9*a11);
  a11=(a4*a11);
  casadi_real a12=sq(a4);
  a12=(a9*a12);
  casadi_real a13=1000.;
  a12=(a12+a13);
  casadi_real a14=(a12*a6);
  a11=(a11+a14);
  a11=(a2*a11);
  a7=(a7+a11);
  a7=(-a7);
  if (res[0]!=0) res[0][1]=a7;
  a7=6.2500000000000000e+001;
  a11=2400000.;
  a14=(a4+a4);
  casadi_real a15=(a14*a6);
  a15=(a11*a15);
  a15=(a1*a15);
  casadi_real a16=sq(a4);
  a16=(a11*a16);
  casadi_real a17=(a16*a0);
  a15=(a15+a17);
  a17=(a4+a4);
  a6=(a17*a6);
  a6=(a9*a6);
  a6=(a1*a6);
  casadi_real a18=sq(a4);
  a18=(a9*a18);
  a18=(a18+a13);
  a0=(a18*a0);
  a6=(a6+a0);
  a15=(a15+a6);
  a15=(a7*a15);
  if (res[0]!=0) res[0][2]=a15;
  a15=0.;
  if (res[0]!=0) res[0][3]=a15;
  a6=-4.7619047619047616e-002;
  a0=arg[3] ? arg[3][4] : 0;
  a13=(a6*a0);
  casadi_real a19=arg[3] ? arg[3][2] : 0;
  casadi_real a20=(a7*a19);
  a13=(a13+a20);
  if (res[0]!=0) res[0][4]=a13;
  a0=(a6*a0);
  a19=(a7*a19);
  a0=(a0+a19);
  a19=arg[3] ? arg[3][3] : 0;
  a0=(a0+a19);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[3] ? arg[3][7] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a19=arg[3] ? arg[3][6] : 0;
  a13=(a5*a19);
  a13=(a3*a13);
  a13=(a2*a13);
  a13=(a1*a13);
  a20=(a8*a0);
  a13=(a13+a20);
  a20=(a10*a19);
  a20=(a9*a20);
  a20=(a4*a20);
  casadi_real a21=(a12*a19);
  a20=(a20+a21);
  a20=(a2*a20);
  a13=(a13+a20);
  a13=(-a13);
  if (res[0]!=0) res[0][7]=a13;
  a13=(a14*a19);
  a13=(a11*a13);
  a13=(a1*a13);
  a20=(a16*a0);
  a13=(a13+a20);
  a19=(a17*a19);
  a19=(a9*a19);
  a19=(a1*a19);
  a0=(a18*a0);
  a19=(a19+a0);
  a13=(a13+a19);
  a13=(a7*a13);
  if (res[0]!=0) res[0][8]=a13;
  if (res[0]!=0) res[0][9]=a15;
  a13=arg[3] ? arg[3][10] : 0;
  a19=(a6*a13);
  a0=arg[3] ? arg[3][8] : 0;
  a20=(a7*a0);
  a19=(a19+a20);
  if (res[0]!=0) res[0][10]=a19;
  a13=(a6*a13);
  a0=(a7*a0);
  a13=(a13+a0);
  a0=arg[3] ? arg[3][9] : 0;
  a13=(a13+a0);
  if (res[0]!=0) res[0][11]=a13;
  a13=arg[3] ? arg[3][13] : 0;
  if (res[0]!=0) res[0][12]=a13;
  a0=arg[3] ? arg[3][12] : 0;
  a19=(a5*a0);
  a19=(a3*a19);
  a19=(a2*a19);
  a19=(a1*a19);
  a20=(a8*a13);
  a19=(a19+a20);
  a20=(a10*a0);
  a20=(a9*a20);
  a20=(a4*a20);
  a21=(a12*a0);
  a20=(a20+a21);
  a20=(a2*a20);
  a19=(a19+a20);
  a19=(-a19);
  if (res[0]!=0) res[0][13]=a19;
  a19=(a14*a0);
  a19=(a11*a19);
  a19=(a1*a19);
  a20=(a16*a13);
  a19=(a19+a20);
  a0=(a17*a0);
  a0=(a9*a0);
  a0=(a1*a0);
  a13=(a18*a13);
  a0=(a0+a13);
  a19=(a19+a0);
  a19=(a7*a19);
  if (res[0]!=0) res[0][14]=a19;
  if (res[0]!=0) res[0][15]=a15;
  a19=arg[3] ? arg[3][16] : 0;
  a0=(a6*a19);
  a13=arg[3] ? arg[3][14] : 0;
  a20=(a7*a13);
  a0=(a0+a20);
  if (res[0]!=0) res[0][16]=a0;
  a19=(a6*a19);
  a13=(a7*a13);
  a19=(a19+a13);
  a13=arg[3] ? arg[3][15] : 0;
  a19=(a19+a13);
  if (res[0]!=0) res[0][17]=a19;
  a19=arg[3] ? arg[3][19] : 0;
  if (res[0]!=0) res[0][18]=a19;
  a13=arg[3] ? arg[3][18] : 0;
  a0=(a5*a13);
  a0=(a3*a0);
  a0=(a2*a0);
  a0=(a1*a0);
  a20=(a8*a19);
  a0=(a0+a20);
  a20=(a10*a13);
  a20=(a9*a20);
  a20=(a4*a20);
  a21=(a12*a13);
  a20=(a20+a21);
  a20=(a2*a20);
  a0=(a0+a20);
  a0=(-a0);
  if (res[0]!=0) res[0][19]=a0;
  a0=(a14*a13);
  a0=(a11*a0);
  a0=(a1*a0);
  a20=(a16*a19);
  a0=(a0+a20);
  a13=(a17*a13);
  a13=(a9*a13);
  a13=(a1*a13);
  a19=(a18*a19);
  a13=(a13+a19);
  a0=(a0+a13);
  a0=(a7*a0);
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a15;
  a0=arg[3] ? arg[3][22] : 0;
  a13=(a6*a0);
  a19=arg[3] ? arg[3][20] : 0;
  a20=(a7*a19);
  a13=(a13+a20);
  if (res[0]!=0) res[0][22]=a13;
  a0=(a6*a0);
  a19=(a7*a19);
  a0=(a0+a19);
  a19=arg[3] ? arg[3][21] : 0;
  a0=(a0+a19);
  if (res[0]!=0) res[0][23]=a0;
  a0=arg[3] ? arg[3][25] : 0;
  if (res[0]!=0) res[0][24]=a0;
  a19=arg[3] ? arg[3][24] : 0;
  a13=(a5*a19);
  a13=(a3*a13);
  a13=(a2*a13);
  a13=(a1*a13);
  a20=(a8*a0);
  a13=(a13+a20);
  a20=(a10*a19);
  a20=(a9*a20);
  a20=(a4*a20);
  a21=(a12*a19);
  a20=(a20+a21);
  a20=(a2*a20);
  a13=(a13+a20);
  a13=(-a13);
  if (res[0]!=0) res[0][25]=a13;
  a13=(a14*a19);
  a13=(a11*a13);
  a13=(a1*a13);
  a20=(a16*a0);
  a13=(a13+a20);
  a19=(a17*a19);
  a19=(a9*a19);
  a19=(a1*a19);
  a0=(a18*a0);
  a19=(a19+a0);
  a13=(a13+a19);
  a13=(a7*a13);
  if (res[0]!=0) res[0][26]=a13;
  if (res[0]!=0) res[0][27]=a15;
  a13=arg[3] ? arg[3][28] : 0;
  a19=(a6*a13);
  a0=arg[3] ? arg[3][26] : 0;
  a20=(a7*a0);
  a19=(a19+a20);
  if (res[0]!=0) res[0][28]=a19;
  a13=(a6*a13);
  a0=(a7*a0);
  a13=(a13+a0);
  a0=arg[3] ? arg[3][27] : 0;
  a13=(a13+a0);
  if (res[0]!=0) res[0][29]=a13;
  a13=arg[3] ? arg[3][31] : 0;
  if (res[0]!=0) res[0][30]=a13;
  a0=arg[3] ? arg[3][30] : 0;
  a5=(a5*a0);
  a5=(a3*a5);
  a5=(a2*a5);
  a5=(a1*a5);
  a19=(a8*a13);
  a5=(a5+a19);
  a10=(a10*a0);
  a10=(a9*a10);
  a10=(a4*a10);
  a19=(a12*a0);
  a10=(a10+a19);
  a10=(a2*a10);
  a5=(a5+a10);
  a5=(-a5);
  if (res[0]!=0) res[0][31]=a5;
  a14=(a14*a0);
  a14=(a11*a14);
  a14=(a1*a14);
  a5=(a16*a13);
  a14=(a14+a5);
  a17=(a17*a0);
  a17=(a9*a17);
  a17=(a1*a17);
  a13=(a18*a13);
  a17=(a17+a13);
  a14=(a14+a17);
  a14=(a7*a14);
  if (res[0]!=0) res[0][32]=a14;
  if (res[0]!=0) res[0][33]=a15;
  a15=arg[3] ? arg[3][34] : 0;
  a14=(a6*a15);
  a17=arg[3] ? arg[3][32] : 0;
  a13=(a7*a17);
  a14=(a14+a13);
  if (res[0]!=0) res[0][34]=a14;
  a15=(a6*a15);
  a17=(a7*a17);
  a15=(a15+a17);
  a17=arg[3] ? arg[3][33] : 0;
  a15=(a15+a17);
  if (res[0]!=0) res[0][35]=a15;
  a15=arg[4] ? arg[4][1] : 0;
  if (res[1]!=0) res[1][0]=a15;
  a17=(a4+a4);
  a14=arg[4] ? arg[4][0] : 0;
  a17=(a17*a14);
  a3=(a3*a17);
  a3=(a2*a3);
  a3=(a1*a3);
  a8=(a8*a15);
  a3=(a3+a8);
  a8=(a4+a4);
  a8=(a8*a14);
  a8=(a9*a8);
  a8=(a4*a8);
  a12=(a12*a14);
  a8=(a8+a12);
  a2=(a2*a8);
  a3=(a3+a2);
  a3=(-a3);
  if (res[1]!=0) res[1][1]=a3;
  a3=1.;
  a2=(a4+a4);
  a2=(a2*a14);
  a11=(a11*a2);
  a11=(a1*a11);
  a16=(a16*a15);
  a11=(a11+a16);
  a4=(a4+a4);
  a4=(a4*a14);
  a9=(a9*a4);
  a1=(a1*a9);
  a18=(a18*a15);
  a1=(a1+a18);
  a11=(a11+a1);
  a11=(a7*a11);
  a11=(a3+a11);
  if (res[1]!=0) res[1][2]=a11;
  if (res[1]!=0) res[1][3]=a3;
  a3=arg[4] ? arg[4][4] : 0;
  a11=(a6*a3);
  a1=arg[4] ? arg[4][2] : 0;
  a18=(a7*a1);
  a11=(a11+a18);
  if (res[1]!=0) res[1][4]=a11;
  a6=(a6*a3);
  a7=(a7*a1);
  a6=(a6+a7);
  a7=arg[4] ? arg[4][3] : 0;
  a6=(a6+a7);
  if (res[1]!=0) res[1][5]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void vdeFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void vdeFun_decref(void) {
}

CASADI_SYMBOL_EXPORT int vdeFun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int vdeFun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* vdeFun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* vdeFun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int vdeFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 22;
  return 0;
}

/* impl_f_fun:(i0[6],i1,i2[3],i3[6])->(o0[6]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[3] ? arg[3][0] : 0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3] ? arg[3][1] : 0;
  casadi_real a2=arg[2] ? arg[2][2] : 0;
  casadi_real a3=20000.;
  casadi_real a4=arg[0] ? arg[0][0] : 0;
  casadi_real a5=sq(a4);
  a3=(a3*a5);
  a5=2000.;
  a3=(a3+a5);
  a5=67.;
  a3=(a3/a5);
  a3=(a3*a1);
  casadi_real a6=1200000.;
  casadi_real a7=sq(a4);
  a7=(a6*a7);
  casadi_real a8=1000.;
  a7=(a7+a8);
  a7=(a7*a4);
  a7=(a7/a5);
  a3=(a3+a7);
  a2=(a2-a3);
  a3=9.8100000000000005e+000;
  a7=arg[2] ? arg[2][1] : 0;
  a3=(a3*a7);
  a2=(a2+a3);
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3] ? arg[3][2] : 0;
  a2=2400000.;
  a3=sq(a4);
  a2=(a2*a3);
  a2=(a2*a1);
  a4=sq(a4);
  a6=(a6*a4);
  a6=(a6+a8);
  a6=(a6*a1);
  a2=(a2+a6);
  a6=1.6000000000000000e-002;
  a2=(a2/a6);
  a1=arg[1] ? arg[1][0] : 0;
  a2=(a2+a1);
  a0=(a0-a2);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3] ? arg[3][3] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[3] ? arg[3][4] : 0;
  a1=-4.7619047619047616e-002;
  a2=arg[0] ? arg[0][4] : 0;
  a8=(a1*a2);
  a4=arg[0] ? arg[0][2] : 0;
  a3=(a4/a6);
  a8=(a8+a3);
  a0=(a0-a8);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[3] ? arg[3][5] : 0;
  a1=(a1*a2);
  a4=(a4/a6);
  a1=(a1+a4);
  a4=arg[0] ? arg[0][3] : 0;
  a1=(a1+a4);
  a0=(a0-a1);
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_f_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 9;
  return 0;
}

/* impl_jac_x_fun:(i0[6],i1,i2[3],i3[6])->(o0[6x6]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  casadi_real a2=1.4925373134328358e-002;
  casadi_real a3=20000.;
  casadi_real a4=arg[0] ? arg[0][0] : 0;
  casadi_real a5=(a4+a4);
  a5=(a3*a5);
  a5=(a2*a5);
  a5=(a1*a5);
  casadi_real a6=1200000.;
  casadi_real a7=(a4+a4);
  a7=(a6*a7);
  a7=(a4*a7);
  casadi_real a8=sq(a4);
  a8=(a6*a8);
  casadi_real a9=1000.;
  a8=(a8+a9);
  a7=(a7+a8);
  a2=(a2*a7);
  a5=(a5+a2);
  if (res[0]!=0) res[0][1]=a5;
  a5=6.2500000000000000e+001;
  a2=2400000.;
  a7=(a4+a4);
  a7=(a2*a7);
  a7=(a1*a7);
  a8=(a4+a4);
  a8=(a6*a8);
  a1=(a1*a8);
  a7=(a7+a1);
  a7=(a5*a7);
  a7=(-a7);
  if (res[0]!=0) res[0][2]=a7;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a7=-1.;
  if (res[0]!=0) res[0][6]=a7;
  a1=sq(a4);
  a3=(a3*a1);
  a1=2000.;
  a3=(a3+a1);
  a1=67.;
  a3=(a3/a1);
  if (res[0]!=0) res[0][7]=a3;
  a3=sq(a4);
  a2=(a2*a3);
  a4=sq(a4);
  a6=(a6*a4);
  a6=(a6+a9);
  a2=(a2+a6);
  a5=(a5*a2);
  a5=(-a5);
  if (res[0]!=0) res[0][8]=a5;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  a5=-6.2500000000000000e+001;
  if (res[0]!=0) res[0][16]=a5;
  if (res[0]!=0) res[0][17]=a5;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a7;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  a7=4.7619047619047616e-002;
  if (res[0]!=0) res[0][28]=a7;
  if (res[0]!=0) res[0][29]=a7;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_x_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_x_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_x_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_x_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}

/* impl_jac_u_fun:(i0[6],i1,i2[3],i3[6])->(o0[6]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  casadi_real a1=-1.;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_u_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_u_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_u_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_u_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* impl_jac_xdot_fun:(i0[6],i1,i2[3],i3[6])->(o0[6x6]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a1;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a1;
  if (res[0]!=0) res[0][34]=a1;
  if (res[0]!=0) res[0][35]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_xdot_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_xdot_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_xdot_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_xdot_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_xdot_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_xdot_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* F:(i0[6],i1,i2[3])->(o0[6]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][0] : 0;
  casadi_real a1=4.1666666666666669e-004;
  casadi_real a2=arg[0] ? arg[0][1] : 0;
  casadi_real a3=2.;
  casadi_real a4=1.2500000000000000e-003;
  casadi_real a5=arg[2] ? arg[2][2] : 0;
  casadi_real a6=20000.;
  casadi_real a7=sq(a0);
  a7=(a6*a7);
  casadi_real a8=2000.;
  a7=(a7+a8);
  casadi_real a9=67.;
  a7=(a7/a9);
  a7=(a7*a2);
  casadi_real a10=1200000.;
  casadi_real a11=sq(a0);
  a11=(a10*a11);
  casadi_real a12=1000.;
  a11=(a11+a12);
  a11=(a11*a0);
  a11=(a11/a9);
  a7=(a7+a11);
  a7=(a5-a7);
  a11=9.8100000000000005e+000;
  casadi_real a13=arg[2] ? arg[2][1] : 0;
  a11=(a11*a13);
  a7=(a7+a11);
  a13=(a4*a7);
  a13=(a2+a13);
  casadi_real a14=(a3*a13);
  a14=(a2+a14);
  casadi_real a15=(a4*a2);
  a15=(a0+a15);
  casadi_real a16=sq(a15);
  a16=(a6*a16);
  a16=(a16+a8);
  a16=(a16/a9);
  a16=(a16*a13);
  casadi_real a17=sq(a15);
  a17=(a10*a17);
  a17=(a17+a12);
  a17=(a17*a15);
  a17=(a17/a9);
  a16=(a16+a17);
  a16=(a5-a16);
  a16=(a16+a11);
  a17=(a4*a16);
  a17=(a2+a17);
  casadi_real a18=(a3*a17);
  a14=(a14+a18);
  a18=2.5000000000000001e-003;
  casadi_real a19=(a4*a13);
  a19=(a0+a19);
  casadi_real a20=sq(a19);
  a20=(a6*a20);
  a20=(a20+a8);
  a20=(a20/a9);
  a20=(a20*a17);
  casadi_real a21=sq(a19);
  a21=(a10*a21);
  a21=(a21+a12);
  a21=(a21*a19);
  a21=(a21/a9);
  a20=(a20+a21);
  a20=(a5-a20);
  a20=(a20+a11);
  a21=(a18*a20);
  a21=(a2+a21);
  a14=(a14+a21);
  a14=(a1*a14);
  a14=(a0+a14);
  a16=(a3*a16);
  a7=(a7+a16);
  a20=(a3*a20);
  a7=(a7+a20);
  a20=(a18*a17);
  a20=(a0+a20);
  a16=sq(a20);
  a16=(a6*a16);
  a16=(a16+a8);
  a16=(a16/a9);
  a16=(a16*a21);
  casadi_real a22=sq(a20);
  a22=(a10*a22);
  a22=(a22+a12);
  a22=(a22*a20);
  a22=(a22/a9);
  a16=(a16+a22);
  a16=(a5-a16);
  a16=(a16+a11);
  a7=(a7+a16);
  a7=(a1*a7);
  a7=(a2+a7);
  a16=sq(a14);
  a16=(a6*a16);
  a16=(a16+a8);
  a16=(a16/a9);
  a16=(a16*a7);
  a22=sq(a14);
  a22=(a10*a22);
  a22=(a22+a12);
  a22=(a22*a14);
  a22=(a22/a9);
  a16=(a16+a22);
  a16=(a5-a16);
  a16=(a16+a11);
  a22=(a4*a16);
  a22=(a7+a22);
  casadi_real a23=(a3*a22);
  a23=(a7+a23);
  casadi_real a24=(a4*a7);
  a24=(a14+a24);
  casadi_real a25=sq(a24);
  a25=(a6*a25);
  a25=(a25+a8);
  a25=(a25/a9);
  a25=(a25*a22);
  casadi_real a26=sq(a24);
  a26=(a10*a26);
  a26=(a26+a12);
  a26=(a26*a24);
  a26=(a26/a9);
  a25=(a25+a26);
  a25=(a5-a25);
  a25=(a25+a11);
  a26=(a4*a25);
  a26=(a7+a26);
  casadi_real a27=(a3*a26);
  a23=(a23+a27);
  a27=(a4*a22);
  a27=(a14+a27);
  casadi_real a28=sq(a27);
  a28=(a6*a28);
  a28=(a28+a8);
  a28=(a28/a9);
  a28=(a28*a26);
  casadi_real a29=sq(a27);
  a29=(a10*a29);
  a29=(a29+a12);
  a29=(a29*a27);
  a29=(a29/a9);
  a28=(a28+a29);
  a28=(a5-a28);
  a28=(a28+a11);
  a29=(a18*a28);
  a29=(a7+a29);
  a23=(a23+a29);
  a23=(a1*a23);
  a23=(a14+a23);
  if (res[0]!=0) res[0][0]=a23;
  a25=(a3*a25);
  a16=(a16+a25);
  a28=(a3*a28);
  a16=(a16+a28);
  a28=(a18*a26);
  a28=(a14+a28);
  a25=sq(a28);
  a6=(a6*a25);
  a6=(a6+a8);
  a6=(a6/a9);
  a6=(a6*a29);
  a8=sq(a28);
  a8=(a10*a8);
  a8=(a8+a12);
  a8=(a8*a28);
  a8=(a8/a9);
  a6=(a6+a8);
  a5=(a5-a6);
  a5=(a5+a11);
  a16=(a16+a5);
  a16=(a1*a16);
  a16=(a7+a16);
  if (res[0]!=0) res[0][1]=a16;
  a16=arg[0] ? arg[0][2] : 0;
  a5=2400000.;
  a11=sq(a0);
  a11=(a5*a11);
  a11=(a11*a2);
  a0=sq(a0);
  a0=(a10*a0);
  a0=(a0+a12);
  a0=(a0*a2);
  a11=(a11+a0);
  a0=1.6000000000000000e-002;
  a11=(a11/a0);
  a2=arg[1] ? arg[1][0] : 0;
  a11=(a11+a2);
  a6=sq(a15);
  a6=(a5*a6);
  a6=(a6*a13);
  a15=sq(a15);
  a15=(a10*a15);
  a15=(a15+a12);
  a15=(a15*a13);
  a6=(a6+a15);
  a6=(a6/a0);
  a6=(a6+a2);
  a15=(a3*a6);
  a15=(a11+a15);
  a13=sq(a19);
  a13=(a5*a13);
  a13=(a13*a17);
  a19=sq(a19);
  a19=(a10*a19);
  a19=(a19+a12);
  a19=(a19*a17);
  a13=(a13+a19);
  a13=(a13/a0);
  a13=(a13+a2);
  a19=(a3*a13);
  a15=(a15+a19);
  a19=sq(a20);
  a19=(a5*a19);
  a19=(a19*a21);
  a20=sq(a20);
  a20=(a10*a20);
  a20=(a20+a12);
  a20=(a20*a21);
  a19=(a19+a20);
  a19=(a19/a0);
  a19=(a19+a2);
  a15=(a15+a19);
  a15=(a1*a15);
  a15=(a16+a15);
  a19=sq(a14);
  a19=(a5*a19);
  a19=(a19*a7);
  a14=sq(a14);
  a14=(a10*a14);
  a14=(a14+a12);
  a14=(a14*a7);
  a19=(a19+a14);
  a19=(a19/a0);
  a19=(a19+a2);
  a14=sq(a24);
  a14=(a5*a14);
  a14=(a14*a22);
  a24=sq(a24);
  a24=(a10*a24);
  a24=(a24+a12);
  a24=(a24*a22);
  a14=(a14+a24);
  a14=(a14/a0);
  a14=(a14+a2);
  a24=(a3*a14);
  a24=(a19+a24);
  a22=sq(a27);
  a22=(a5*a22);
  a22=(a22*a26);
  a27=sq(a27);
  a27=(a10*a27);
  a27=(a27+a12);
  a27=(a27*a26);
  a22=(a22+a27);
  a22=(a22/a0);
  a22=(a22+a2);
  a27=(a3*a22);
  a24=(a24+a27);
  a27=sq(a28);
  a5=(a5*a27);
  a5=(a5*a29);
  a28=sq(a28);
  a10=(a10*a28);
  a10=(a10+a12);
  a10=(a10*a29);
  a5=(a5+a10);
  a5=(a5/a0);
  a5=(a5+a2);
  a24=(a24+a5);
  a24=(a1*a24);
  a24=(a15+a24);
  if (res[0]!=0) res[0][2]=a24;
  a24=arg[0] ? arg[0][3] : 0;
  a5=(a3*a2);
  a5=(a2+a5);
  a10=(a3*a2);
  a5=(a5+a10);
  a5=(a5+a2);
  a5=(a1*a5);
  a5=(a24+a5);
  a10=(a3*a2);
  a10=(a2+a10);
  a29=(a3*a2);
  a10=(a10+a29);
  a10=(a10+a2);
  a10=(a1*a10);
  a10=(a5+a10);
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[0] ? arg[0][4] : 0;
  a29=-4.7619047619047616e-002;
  a12=(a29*a10);
  a28=(a16/a0);
  a12=(a12+a28);
  a28=(a4*a12);
  a28=(a10+a28);
  a27=(a29*a28);
  a11=(a4*a11);
  a11=(a16+a11);
  a26=(a11/a0);
  a27=(a27+a26);
  a26=(a3*a27);
  a12=(a12+a26);
  a27=(a4*a27);
  a27=(a10+a27);
  a26=(a29*a27);
  a6=(a4*a6);
  a6=(a16+a6);
  a7=(a6/a0);
  a26=(a26+a7);
  a7=(a3*a26);
  a12=(a12+a7);
  a26=(a18*a26);
  a26=(a10+a26);
  a7=(a29*a26);
  a13=(a18*a13);
  a13=(a16+a13);
  a20=(a13/a0);
  a7=(a7+a20);
  a12=(a12+a7);
  a12=(a1*a12);
  a12=(a10+a12);
  a7=(a29*a12);
  a20=(a15/a0);
  a7=(a7+a20);
  a20=(a4*a7);
  a20=(a12+a20);
  a21=(a29*a20);
  a19=(a4*a19);
  a19=(a15+a19);
  a17=(a19/a0);
  a21=(a21+a17);
  a17=(a3*a21);
  a7=(a7+a17);
  a21=(a4*a21);
  a21=(a12+a21);
  a17=(a29*a21);
  a14=(a4*a14);
  a14=(a15+a14);
  a8=(a14/a0);
  a17=(a17+a8);
  a8=(a3*a17);
  a7=(a7+a8);
  a17=(a18*a17);
  a17=(a12+a17);
  a8=(a29*a17);
  a22=(a18*a22);
  a22=(a15+a22);
  a9=(a22/a0);
  a8=(a8+a9);
  a7=(a7+a8);
  a7=(a1*a7);
  a7=(a12+a7);
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[0] ? arg[0][5] : 0;
  a10=(a29*a10);
  a16=(a16/a0);
  a10=(a10+a16);
  a10=(a10+a24);
  a28=(a29*a28);
  a11=(a11/a0);
  a28=(a28+a11);
  a11=(a4*a2);
  a11=(a24+a11);
  a28=(a28+a11);
  a28=(a3*a28);
  a10=(a10+a28);
  a27=(a29*a27);
  a6=(a6/a0);
  a27=(a27+a6);
  a6=(a4*a2);
  a6=(a24+a6);
  a27=(a27+a6);
  a27=(a3*a27);
  a10=(a10+a27);
  a26=(a29*a26);
  a13=(a13/a0);
  a26=(a26+a13);
  a13=(a18*a2);
  a24=(a24+a13);
  a26=(a26+a24);
  a10=(a10+a26);
  a10=(a1*a10);
  a7=(a7+a10);
  a12=(a29*a12);
  a15=(a15/a0);
  a12=(a12+a15);
  a12=(a12+a5);
  a20=(a29*a20);
  a19=(a19/a0);
  a20=(a20+a19);
  a19=(a4*a2);
  a19=(a5+a19);
  a20=(a20+a19);
  a20=(a3*a20);
  a12=(a12+a20);
  a21=(a29*a21);
  a14=(a14/a0);
  a21=(a21+a14);
  a4=(a4*a2);
  a4=(a5+a4);
  a21=(a21+a4);
  a3=(a3*a21);
  a12=(a12+a3);
  a29=(a29*a17);
  a22=(a22/a0);
  a29=(a29+a22);
  a18=(a18*a2);
  a5=(a5+a18);
  a29=(a29+a5);
  a12=(a12+a29);
  a1=(a1*a12);
  a7=(a7+a1);
  if (res[0]!=0) res[0][5]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int F(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void F_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_decref(void) {
}

CASADI_SYMBOL_EXPORT int F_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* F_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* F_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* F_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 30;
  return 0;
}

/* D:(i0[6],i1,i2[3])->(o0[6x6],o1[6]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  casadi_real a1=4.1666666666666669e-004;
  casadi_real a2=2.;
  casadi_real a3=1.2500000000000000e-003;
  casadi_real a4=arg[0] ? arg[0][1] : 0;
  casadi_real a5=1.4925373134328358e-002;
  casadi_real a6=20000.;
  casadi_real a7=arg[0] ? arg[0][0] : 0;
  casadi_real a8=(a7+a7);
  a8=(a6*a8);
  a8=(a5*a8);
  a8=(a4*a8);
  casadi_real a9=1200000.;
  casadi_real a10=(a7+a7);
  a10=(a9*a10);
  a10=(a7*a10);
  casadi_real a11=sq(a7);
  a11=(a9*a11);
  casadi_real a12=1000.;
  a11=(a11+a12);
  a10=(a10+a11);
  a10=(a5*a10);
  a8=(a8+a10);
  a10=(a3*a8);
  casadi_real a13=(a2*a10);
  casadi_real a14=arg[2] ? arg[2][2] : 0;
  casadi_real a15=sq(a7);
  a15=(a6*a15);
  casadi_real a16=2000.;
  a15=(a15+a16);
  casadi_real a17=67.;
  a15=(a15/a17);
  casadi_real a18=(a15*a4);
  a11=(a11*a7);
  a11=(a11/a17);
  a18=(a18+a11);
  a18=(a14-a18);
  a11=9.8100000000000005e+000;
  casadi_real a19=arg[2] ? arg[2][1] : 0;
  a11=(a11*a19);
  a18=(a18+a11);
  a19=(a3*a18);
  a19=(a4+a19);
  casadi_real a20=(a3*a4);
  a20=(a7+a20);
  casadi_real a21=(a20+a20);
  casadi_real a22=(a6*a21);
  a22=(a5*a22);
  a22=(a19*a22);
  casadi_real a23=sq(a20);
  a23=(a6*a23);
  a23=(a23+a16);
  a23=(a23/a17);
  casadi_real a24=(a23*a10);
  a22=(a22-a24);
  a24=(a20+a20);
  casadi_real a25=(a9*a24);
  a25=(a20*a25);
  casadi_real a26=sq(a20);
  a26=(a9*a26);
  a26=(a26+a12);
  a25=(a25+a26);
  a25=(a5*a25);
  a22=(a22+a25);
  a25=(a3*a22);
  casadi_real a27=(a2*a25);
  a13=(a13+a27);
  a27=2.5000000000000001e-003;
  casadi_real a28=(a23*a19);
  casadi_real a29=(a26*a20);
  a29=(a29/a17);
  a28=(a28+a29);
  a28=(a14-a28);
  a28=(a28+a11);
  a29=(a3*a28);
  a29=(a4+a29);
  casadi_real a30=(a3*a19);
  a30=(a7+a30);
  casadi_real a31=(a30+a30);
  casadi_real a32=(a3*a10);
  a32=(a0-a32);
  casadi_real a33=(a31*a32);
  a33=(a6*a33);
  a33=(a5*a33);
  a33=(a29*a33);
  casadi_real a34=sq(a30);
  a34=(a6*a34);
  a34=(a34+a16);
  a34=(a34/a17);
  casadi_real a35=(a34*a25);
  a33=(a33-a35);
  a35=(a30+a30);
  casadi_real a36=(a35*a32);
  a36=(a9*a36);
  a36=(a30*a36);
  casadi_real a37=sq(a30);
  a37=(a9*a37);
  a37=(a37+a12);
  casadi_real a38=(a37*a32);
  a36=(a36+a38);
  a36=(a5*a36);
  a33=(a33+a36);
  a36=(a27*a33);
  a13=(a13+a36);
  a13=(a1*a13);
  a13=(a0-a13);
  a22=(a2*a22);
  a8=(a8+a22);
  a33=(a2*a33);
  a8=(a8+a33);
  a33=(a34*a29);
  a22=(a37*a30);
  a22=(a22/a17);
  a33=(a33+a22);
  a33=(a14-a33);
  a33=(a33+a11);
  a22=(a27*a33);
  a22=(a4+a22);
  a38=(a27*a29);
  a38=(a7+a38);
  casadi_real a39=(a38+a38);
  casadi_real a40=(a27*a25);
  a40=(a0-a40);
  casadi_real a41=(a39*a40);
  a41=(a6*a41);
  a41=(a5*a41);
  a41=(a22*a41);
  casadi_real a42=sq(a38);
  a42=(a6*a42);
  a42=(a42+a16);
  a42=(a42/a17);
  casadi_real a43=(a42*a36);
  a41=(a41-a43);
  a43=(a38+a38);
  casadi_real a44=(a43*a40);
  a44=(a9*a44);
  a44=(a38*a44);
  casadi_real a45=sq(a38);
  a45=(a9*a45);
  a45=(a45+a12);
  casadi_real a46=(a45*a40);
  a44=(a44+a46);
  a44=(a5*a44);
  a41=(a41+a44);
  a8=(a8+a41);
  a8=(a1*a8);
  a28=(a2*a28);
  a18=(a18+a28);
  a33=(a2*a33);
  a18=(a18+a33);
  a33=(a42*a22);
  a28=(a45*a38);
  a28=(a28/a17);
  a33=(a33+a28);
  a33=(a14-a33);
  a33=(a33+a11);
  a18=(a18+a33);
  a18=(a1*a18);
  a18=(a4+a18);
  a33=(a2*a19);
  a33=(a4+a33);
  a28=(a2*a29);
  a33=(a33+a28);
  a33=(a33+a22);
  a33=(a1*a33);
  a33=(a7+a33);
  a28=(a33+a33);
  a41=(a28*a13);
  a41=(a6*a41);
  a41=(a5*a41);
  a41=(a18*a41);
  a44=sq(a33);
  a44=(a6*a44);
  a44=(a44+a16);
  a44=(a44/a17);
  a46=(a44*a8);
  a41=(a41-a46);
  a46=(a33+a33);
  casadi_real a47=(a46*a13);
  a47=(a9*a47);
  a47=(a33*a47);
  casadi_real a48=sq(a33);
  a48=(a9*a48);
  a48=(a48+a12);
  casadi_real a49=(a48*a13);
  a47=(a47+a49);
  a47=(a5*a47);
  a41=(a41+a47);
  a47=(a3*a41);
  a47=(a8+a47);
  a49=(a2*a47);
  a49=(a8+a49);
  casadi_real a50=(a44*a18);
  casadi_real a51=(a48*a33);
  a51=(a51/a17);
  a50=(a50+a51);
  a50=(a14-a50);
  a50=(a50+a11);
  a50=(a3*a50);
  a50=(a18+a50);
  a51=(a3*a18);
  a51=(a33+a51);
  casadi_real a52=(a51+a51);
  casadi_real a53=(a3*a8);
  a53=(a13-a53);
  casadi_real a54=(a52*a53);
  a54=(a6*a54);
  a54=(a5*a54);
  a54=(a50*a54);
  casadi_real a55=sq(a51);
  a55=(a6*a55);
  a55=(a55+a16);
  a55=(a55/a17);
  casadi_real a56=(a55*a47);
  a54=(a54-a56);
  a56=(a51+a51);
  casadi_real a57=(a56*a53);
  a57=(a9*a57);
  a57=(a51*a57);
  casadi_real a58=sq(a51);
  a58=(a9*a58);
  a58=(a58+a12);
  casadi_real a59=(a58*a53);
  a57=(a57+a59);
  a57=(a5*a57);
  a54=(a54+a57);
  a57=(a3*a54);
  a57=(a8+a57);
  a59=(a2*a57);
  a49=(a49+a59);
  a59=(a55*a50);
  casadi_real a60=(a58*a51);
  a60=(a60/a17);
  a59=(a59+a60);
  a59=(a14-a59);
  a59=(a59+a11);
  a59=(a3*a59);
  a59=(a18+a59);
  a60=(a3*a50);
  a60=(a33+a60);
  casadi_real a61=(a60+a60);
  casadi_real a62=(a3*a47);
  a62=(a13-a62);
  casadi_real a63=(a61*a62);
  a63=(a6*a63);
  a63=(a5*a63);
  a63=(a59*a63);
  casadi_real a64=sq(a60);
  a64=(a6*a64);
  a64=(a64+a16);
  a64=(a64/a17);
  casadi_real a65=(a64*a57);
  a63=(a63-a65);
  a65=(a60+a60);
  casadi_real a66=(a65*a62);
  a66=(a9*a66);
  a66=(a60*a66);
  casadi_real a67=sq(a60);
  a67=(a9*a67);
  a67=(a67+a12);
  casadi_real a68=(a67*a62);
  a66=(a66+a68);
  a66=(a5*a66);
  a63=(a63+a66);
  a66=(a27*a63);
  a66=(a8+a66);
  a49=(a49+a66);
  a49=(a1*a49);
  a49=(a13-a49);
  if (res[0]!=0) res[0][0]=a49;
  a54=(a2*a54);
  a41=(a41+a54);
  a63=(a2*a63);
  a41=(a41+a63);
  a63=(a64*a59);
  a54=(a67*a60);
  a54=(a54/a17);
  a63=(a63+a54);
  a14=(a14-a63);
  a14=(a14+a11);
  a14=(a27*a14);
  a14=(a18+a14);
  a11=(a27*a59);
  a11=(a33+a11);
  a63=(a11+a11);
  a54=(a27*a57);
  a54=(a13-a54);
  a49=(a63*a54);
  a49=(a6*a49);
  a49=(a5*a49);
  a49=(a14*a49);
  a68=sq(a11);
  a68=(a6*a68);
  a68=(a68+a16);
  a68=(a68/a17);
  a17=(a68*a66);
  a49=(a49-a17);
  a17=(a11+a11);
  a16=(a17*a54);
  a16=(a9*a16);
  a16=(a11*a16);
  casadi_real a69=sq(a11);
  a69=(a9*a69);
  a69=(a69+a12);
  casadi_real a70=(a69*a54);
  a16=(a16+a70);
  a16=(a5*a16);
  a49=(a49+a16);
  a41=(a41+a49);
  a41=(a1*a41);
  a41=(a8+a41);
  a41=(-a41);
  if (res[0]!=0) res[0][1]=a41;
  a41=6.2500000000000000e+001;
  a49=2400000.;
  a16=(a7+a7);
  a16=(a49*a16);
  a16=(a4*a16);
  a70=(a7+a7);
  a70=(a9*a70);
  a4=(a4*a70);
  a16=(a16+a4);
  a16=(a41*a16);
  a4=(a20+a20);
  a70=(a49*a4);
  a70=(a19*a70);
  casadi_real a71=sq(a20);
  a71=(a49*a71);
  casadi_real a72=(a71*a10);
  a70=(a70-a72);
  a72=(a20+a20);
  casadi_real a73=(a9*a72);
  a73=(a19*a73);
  casadi_real a74=sq(a20);
  a74=(a9*a74);
  a74=(a74+a12);
  a10=(a74*a10);
  a73=(a73-a10);
  a70=(a70+a73);
  a70=(a41*a70);
  a73=(a2*a70);
  a73=(a16+a73);
  a10=(a30+a30);
  casadi_real a75=(a10*a32);
  a75=(a49*a75);
  a75=(a29*a75);
  casadi_real a76=sq(a30);
  a76=(a49*a76);
  casadi_real a77=(a76*a25);
  a75=(a75-a77);
  a77=(a30+a30);
  a32=(a77*a32);
  a32=(a9*a32);
  a32=(a29*a32);
  casadi_real a78=sq(a30);
  a78=(a9*a78);
  a78=(a78+a12);
  a25=(a78*a25);
  a32=(a32-a25);
  a75=(a75+a32);
  a75=(a41*a75);
  a32=(a2*a75);
  a73=(a73+a32);
  a32=(a38+a38);
  a25=(a32*a40);
  a25=(a49*a25);
  a25=(a22*a25);
  casadi_real a79=sq(a38);
  a79=(a49*a79);
  casadi_real a80=(a79*a36);
  a25=(a25-a80);
  a80=(a38+a38);
  a40=(a80*a40);
  a40=(a9*a40);
  a40=(a22*a40);
  casadi_real a81=sq(a38);
  a81=(a9*a81);
  a81=(a81+a12);
  a36=(a81*a36);
  a40=(a40-a36);
  a25=(a25+a40);
  a25=(a41*a25);
  a73=(a73+a25);
  a73=(a1*a73);
  a25=(a33+a33);
  a40=(a25*a13);
  a40=(a49*a40);
  a40=(a18*a40);
  a36=sq(a33);
  a36=(a49*a36);
  casadi_real a82=(a36*a8);
  a40=(a40-a82);
  a82=(a33+a33);
  a13=(a82*a13);
  a13=(a9*a13);
  a13=(a18*a13);
  casadi_real a83=sq(a33);
  a83=(a9*a83);
  a83=(a83+a12);
  a8=(a83*a8);
  a13=(a13-a8);
  a40=(a40+a13);
  a40=(a41*a40);
  a13=(a51+a51);
  a8=(a13*a53);
  a8=(a49*a8);
  a8=(a50*a8);
  casadi_real a84=sq(a51);
  a84=(a49*a84);
  casadi_real a85=(a84*a47);
  a8=(a8-a85);
  a85=(a51+a51);
  a53=(a85*a53);
  a53=(a9*a53);
  a53=(a50*a53);
  casadi_real a86=sq(a51);
  a86=(a9*a86);
  a86=(a86+a12);
  a47=(a86*a47);
  a53=(a53-a47);
  a8=(a8+a53);
  a8=(a41*a8);
  a53=(a2*a8);
  a53=(a40+a53);
  a47=(a60+a60);
  casadi_real a87=(a47*a62);
  a87=(a49*a87);
  a87=(a59*a87);
  casadi_real a88=sq(a60);
  a88=(a49*a88);
  casadi_real a89=(a88*a57);
  a87=(a87-a89);
  a89=(a60+a60);
  a62=(a89*a62);
  a62=(a9*a62);
  a62=(a59*a62);
  casadi_real a90=sq(a60);
  a90=(a9*a90);
  a90=(a90+a12);
  a57=(a90*a57);
  a62=(a62-a57);
  a87=(a87+a62);
  a87=(a41*a87);
  a62=(a2*a87);
  a53=(a53+a62);
  a62=(a11+a11);
  a57=(a62*a54);
  a57=(a49*a57);
  a57=(a14*a57);
  casadi_real a91=sq(a11);
  a91=(a49*a91);
  casadi_real a92=(a91*a66);
  a57=(a57-a92);
  a92=(a11+a11);
  a54=(a92*a54);
  a54=(a9*a54);
  a54=(a14*a54);
  casadi_real a93=sq(a11);
  a93=(a9*a93);
  a93=(a93+a12);
  a66=(a93*a66);
  a54=(a54-a66);
  a57=(a57+a54);
  a57=(a41*a57);
  a53=(a53+a57);
  a53=(a1*a53);
  a53=(a73+a53);
  if (res[0]!=0) res[0][2]=a53;
  a53=0.;
  if (res[0]!=0) res[0][3]=a53;
  a16=(a3*a16);
  a57=(a41*a16);
  a54=(a2*a57);
  a66=-4.7619047619047616e-002;
  a57=(a3*a57);
  casadi_real a94=(a66*a57);
  a70=(a3*a70);
  casadi_real a95=(a41*a70);
  a94=(a94+a95);
  a95=(a2*a94);
  a54=(a54+a95);
  a94=(a27*a94);
  a95=(a66*a94);
  a75=(a27*a75);
  casadi_real a96=(a41*a75);
  a95=(a95+a96);
  a54=(a54+a95);
  a54=(a1*a54);
  a95=(a66*a54);
  a96=(a41*a73);
  a95=(a95+a96);
  a96=(a3*a95);
  a96=(a54+a96);
  casadi_real a97=(a66*a96);
  a40=(a3*a40);
  a40=(a73+a40);
  casadi_real a98=(a41*a40);
  a97=(a97+a98);
  a98=(a2*a97);
  a95=(a95+a98);
  a97=(a3*a97);
  a97=(a54+a97);
  a98=(a66*a97);
  a8=(a3*a8);
  a8=(a73+a8);
  casadi_real a99=(a41*a8);
  a98=(a98+a99);
  a99=(a2*a98);
  a95=(a95+a99);
  a98=(a27*a98);
  a98=(a54+a98);
  a99=(a66*a98);
  a87=(a27*a87);
  a87=(a73+a87);
  casadi_real a100=(a41*a87);
  a99=(a99+a100);
  a95=(a95+a99);
  a95=(a1*a95);
  a95=(a54+a95);
  if (res[0]!=0) res[0][4]=a95;
  a16=(a41*a16);
  a16=(a2*a16);
  a57=(a66*a57);
  a70=(a41*a70);
  a57=(a57+a70);
  a57=(a2*a57);
  a16=(a16+a57);
  a94=(a66*a94);
  a75=(a41*a75);
  a94=(a94+a75);
  a16=(a16+a94);
  a16=(a1*a16);
  a54=(a66*a54);
  a73=(a41*a73);
  a54=(a54+a73);
  a96=(a66*a96);
  a40=(a41*a40);
  a96=(a96+a40);
  a96=(a2*a96);
  a54=(a54+a96);
  a97=(a66*a97);
  a8=(a41*a8);
  a97=(a97+a8);
  a97=(a2*a97);
  a54=(a54+a97);
  a98=(a66*a98);
  a87=(a41*a87);
  a98=(a98+a87);
  a54=(a54+a98);
  a54=(a1*a54);
  a16=(a16+a54);
  if (res[0]!=0) res[0][5]=a16;
  a16=(a3*a15);
  a16=(a0-a16);
  a54=(a2*a16);
  a54=(a0+a54);
  a21=(a3*a21);
  a21=(a6*a21);
  a21=(a5*a21);
  a21=(a19*a21);
  a23=(a23*a16);
  a21=(a21+a23);
  a24=(a3*a24);
  a24=(a9*a24);
  a20=(a20*a24);
  a26=(a3*a26);
  a20=(a20+a26);
  a20=(a5*a20);
  a21=(a21+a20);
  a20=(a3*a21);
  a20=(a0-a20);
  a26=(a2*a20);
  a54=(a54+a26);
  a26=(a3*a16);
  a31=(a31*a26);
  a31=(a6*a31);
  a31=(a5*a31);
  a31=(a29*a31);
  a34=(a34*a20);
  a31=(a31+a34);
  a35=(a35*a26);
  a35=(a9*a35);
  a30=(a30*a35);
  a37=(a37*a26);
  a30=(a30+a37);
  a30=(a5*a30);
  a31=(a31+a30);
  a30=(a27*a31);
  a30=(a0-a30);
  a54=(a54+a30);
  a54=(a1*a54);
  a21=(a2*a21);
  a15=(a15+a21);
  a31=(a2*a31);
  a15=(a15+a31);
  a31=(a27*a20);
  a39=(a39*a31);
  a39=(a6*a39);
  a39=(a5*a39);
  a39=(a22*a39);
  a42=(a42*a30);
  a39=(a39+a42);
  a43=(a43*a31);
  a43=(a9*a43);
  a38=(a38*a43);
  a45=(a45*a31);
  a38=(a38+a45);
  a38=(a5*a38);
  a39=(a39+a38);
  a15=(a15+a39);
  a15=(a1*a15);
  a15=(a0-a15);
  a28=(a28*a54);
  a28=(a6*a28);
  a28=(a5*a28);
  a28=(a18*a28);
  a44=(a44*a15);
  a28=(a28+a44);
  a46=(a46*a54);
  a46=(a9*a46);
  a33=(a33*a46);
  a48=(a48*a54);
  a33=(a33+a48);
  a33=(a5*a33);
  a28=(a28+a33);
  a33=(a3*a28);
  a33=(a15-a33);
  a48=(a2*a33);
  a48=(a15+a48);
  a46=(a3*a15);
  a46=(a54+a46);
  a52=(a52*a46);
  a52=(a6*a52);
  a52=(a5*a52);
  a52=(a50*a52);
  a55=(a55*a33);
  a52=(a52+a55);
  a56=(a56*a46);
  a56=(a9*a56);
  a51=(a51*a56);
  a58=(a58*a46);
  a51=(a51+a58);
  a51=(a5*a51);
  a52=(a52+a51);
  a51=(a3*a52);
  a51=(a15-a51);
  a58=(a2*a51);
  a48=(a48+a58);
  a58=(a3*a33);
  a58=(a54+a58);
  a61=(a61*a58);
  a61=(a6*a61);
  a61=(a5*a61);
  a61=(a59*a61);
  a64=(a64*a51);
  a61=(a61+a64);
  a65=(a65*a58);
  a65=(a9*a65);
  a60=(a60*a65);
  a67=(a67*a58);
  a60=(a60+a67);
  a60=(a5*a60);
  a61=(a61+a60);
  a60=(a27*a61);
  a60=(a15-a60);
  a48=(a48+a60);
  a48=(a1*a48);
  a48=(a54+a48);
  if (res[0]!=0) res[0][6]=a48;
  a52=(a2*a52);
  a28=(a28+a52);
  a61=(a2*a61);
  a28=(a28+a61);
  a61=(a27*a51);
  a61=(a54+a61);
  a63=(a63*a61);
  a6=(a6*a63);
  a6=(a5*a6);
  a6=(a14*a6);
  a68=(a68*a60);
  a6=(a6+a68);
  a17=(a17*a61);
  a17=(a9*a17);
  a11=(a11*a17);
  a69=(a69*a61);
  a11=(a11+a69);
  a5=(a5*a11);
  a6=(a6+a5);
  a28=(a28+a6);
  a28=(a1*a28);
  a28=(a15-a28);
  if (res[0]!=0) res[0][7]=a28;
  a28=sq(a7);
  a28=(a49*a28);
  a7=sq(a7);
  a7=(a9*a7);
  a7=(a7+a12);
  a28=(a28+a7);
  a28=(a41*a28);
  a4=(a3*a4);
  a4=(a49*a4);
  a4=(a19*a4);
  a71=(a71*a16);
  a4=(a4+a71);
  a72=(a3*a72);
  a72=(a9*a72);
  a19=(a19*a72);
  a74=(a74*a16);
  a19=(a19+a74);
  a4=(a4+a19);
  a4=(a41*a4);
  a19=(a2*a4);
  a19=(a28+a19);
  a10=(a10*a26);
  a10=(a49*a10);
  a10=(a29*a10);
  a76=(a76*a20);
  a10=(a10+a76);
  a77=(a77*a26);
  a77=(a9*a77);
  a29=(a29*a77);
  a78=(a78*a20);
  a29=(a29+a78);
  a10=(a10+a29);
  a10=(a41*a10);
  a29=(a2*a10);
  a19=(a19+a29);
  a32=(a32*a31);
  a32=(a49*a32);
  a32=(a22*a32);
  a79=(a79*a30);
  a32=(a32+a79);
  a80=(a80*a31);
  a80=(a9*a80);
  a22=(a22*a80);
  a81=(a81*a30);
  a22=(a22+a81);
  a32=(a32+a22);
  a32=(a41*a32);
  a19=(a19+a32);
  a19=(a1*a19);
  a25=(a25*a54);
  a25=(a49*a25);
  a25=(a18*a25);
  a36=(a36*a15);
  a25=(a25+a36);
  a82=(a82*a54);
  a82=(a9*a82);
  a18=(a18*a82);
  a83=(a83*a15);
  a18=(a18+a83);
  a25=(a25+a18);
  a25=(a41*a25);
  a13=(a13*a46);
  a13=(a49*a13);
  a13=(a50*a13);
  a84=(a84*a33);
  a13=(a13+a84);
  a85=(a85*a46);
  a85=(a9*a85);
  a50=(a50*a85);
  a86=(a86*a33);
  a50=(a50+a86);
  a13=(a13+a50);
  a13=(a41*a13);
  a50=(a2*a13);
  a50=(a25+a50);
  a47=(a47*a58);
  a47=(a49*a47);
  a47=(a59*a47);
  a88=(a88*a51);
  a47=(a47+a88);
  a89=(a89*a58);
  a89=(a9*a89);
  a59=(a59*a89);
  a90=(a90*a51);
  a59=(a59+a90);
  a47=(a47+a59);
  a47=(a41*a47);
  a59=(a2*a47);
  a50=(a50+a59);
  a62=(a62*a61);
  a49=(a49*a62);
  a49=(a14*a49);
  a91=(a91*a60);
  a49=(a49+a91);
  a92=(a92*a61);
  a9=(a9*a92);
  a14=(a14*a9);
  a93=(a93*a60);
  a14=(a14+a93);
  a49=(a49+a14);
  a49=(a41*a49);
  a50=(a50+a49);
  a50=(a1*a50);
  a50=(a19+a50);
  if (res[0]!=0) res[0][8]=a50;
  if (res[0]!=0) res[0][9]=a53;
  a28=(a3*a28);
  a50=(a41*a28);
  a49=(a2*a50);
  a50=(a3*a50);
  a14=(a66*a50);
  a4=(a3*a4);
  a93=(a41*a4);
  a14=(a14+a93);
  a93=(a2*a14);
  a49=(a49+a93);
  a14=(a27*a14);
  a93=(a66*a14);
  a10=(a27*a10);
  a60=(a41*a10);
  a93=(a93+a60);
  a49=(a49+a93);
  a49=(a1*a49);
  a93=(a66*a49);
  a60=(a41*a19);
  a93=(a93+a60);
  a60=(a3*a93);
  a60=(a49+a60);
  a9=(a66*a60);
  a25=(a3*a25);
  a25=(a19+a25);
  a92=(a41*a25);
  a9=(a9+a92);
  a92=(a2*a9);
  a93=(a93+a92);
  a9=(a3*a9);
  a9=(a49+a9);
  a92=(a66*a9);
  a3=(a3*a13);
  a3=(a19+a3);
  a13=(a41*a3);
  a92=(a92+a13);
  a13=(a2*a92);
  a93=(a93+a13);
  a92=(a27*a92);
  a92=(a49+a92);
  a13=(a66*a92);
  a27=(a27*a47);
  a27=(a19+a27);
  a47=(a41*a27);
  a13=(a13+a47);
  a93=(a93+a13);
  a93=(a1*a93);
  a93=(a49+a93);
  if (res[0]!=0) res[0][10]=a93;
  a28=(a41*a28);
  a28=(a2*a28);
  a50=(a66*a50);
  a4=(a41*a4);
  a50=(a50+a4);
  a50=(a2*a50);
  a28=(a28+a50);
  a14=(a66*a14);
  a10=(a41*a10);
  a14=(a14+a10);
  a28=(a28+a14);
  a28=(a1*a28);
  a49=(a66*a49);
  a19=(a41*a19);
  a49=(a49+a19);
  a60=(a66*a60);
  a25=(a41*a25);
  a60=(a60+a25);
  a60=(a2*a60);
  a49=(a49+a60);
  a9=(a66*a9);
  a3=(a41*a3);
  a9=(a9+a3);
  a2=(a2*a9);
  a49=(a49+a2);
  a66=(a66*a92);
  a41=(a41*a27);
  a66=(a66+a41);
  a49=(a49+a66);
  a1=(a1*a49);
  a28=(a28+a1);
  if (res[0]!=0) res[0][11]=a28;
  if (res[0]!=0) res[0][12]=a53;
  if (res[0]!=0) res[0][13]=a53;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a53;
  a28=3.1246280057144182e-001;
  if (res[0]!=0) res[0][16]=a28;
  if (res[0]!=0) res[0][17]=a28;
  if (res[0]!=0) res[0][18]=a53;
  if (res[0]!=0) res[0][19]=a53;
  if (res[0]!=0) res[0][20]=a53;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a53;
  a28=5.0000000000000001e-003;
  if (res[0]!=0) res[0][23]=a28;
  if (res[0]!=0) res[0][24]=a53;
  if (res[0]!=0) res[0][25]=a53;
  if (res[0]!=0) res[0][26]=a53;
  if (res[0]!=0) res[0][27]=a53;
  a1=9.9976193310432648e-001;
  if (res[0]!=0) res[0][28]=a1;
  a1=-2.3806689567347947e-004;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a53;
  if (res[0]!=0) res[0][31]=a53;
  if (res[0]!=0) res[0][32]=a53;
  if (res[0]!=0) res[0][33]=a53;
  if (res[0]!=0) res[0][34]=a53;
  if (res[0]!=0) res[0][35]=a0;
  if (res[1]!=0) res[1][0]=a53;
  if (res[1]!=0) res[1][1]=a53;
  if (res[1]!=0) res[1][2]=a28;
  if (res[1]!=0) res[1][3]=a28;
  a28=7.8118799972229369e-004;
  if (res[1]!=0) res[1][4]=a28;
  a28=7.9368799972229383e-004;
  if (res[1]!=0) res[1][5]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int D(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void D_incref(void) {
}

CASADI_SYMBOL_EXPORT void D_decref(void) {
}

CASADI_SYMBOL_EXPORT int D_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int D_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* D_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* D_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* D_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* D_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int D_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 101;
  return 0;
}

/* h_fun:(states[6],controls,params[3])->(h[2]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][5] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int h_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* h_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_fun_name_out(int i){
  switch (i) {
    case 0: return "h";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* h_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* h_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int h_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* path_con_fun:(states[6],controls,params[3])->(path_con[]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int path_con_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_out(int i){
  switch (i) {
    case 0: return "path_con";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* path_con_N_fun:(states[6],params[3])->(path_con_N[]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_out(int i){
  switch (i) {
    case 0: return "path_con_N";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obji_fun:(i0[6],i1,i2[3],i3[2],i4[2x2])->(o0) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[4] ? arg[4][0] : 0;
  a1=sqrt(a1);
  casadi_real a2=arg[0] ? arg[0][5] : 0;
  casadi_real a3=arg[3] ? arg[3][0] : 0;
  a2=(a2-a3);
  a1=(a1*a2);
  a3=arg[4] ? arg[4][2] : 0;
  a3=sqrt(a3);
  casadi_real a4=arg[0] ? arg[0][3] : 0;
  casadi_real a5=arg[3] ? arg[3][1] : 0;
  a4=(a4-a5);
  a3=(a3*a4);
  a1=(a1+a3);
  a1=sq(a1);
  a3=arg[4] ? arg[4][1] : 0;
  a3=sqrt(a3);
  a3=(a3*a2);
  a2=arg[4] ? arg[4][3] : 0;
  a2=sqrt(a2);
  a2=(a2*a4);
  a3=(a3+a2);
  a3=sq(a3);
  a1=(a1+a3);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void obji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void obji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int obji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int obji_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obji_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obji_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obji_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}

/* objN_fun:(i0[6],i1[3],i2,i3)->(o0) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[3] ? arg[3][0] : 0;
  a1=sqrt(a1);
  casadi_real a2=arg[0] ? arg[0][3] : 0;
  casadi_real a3=arg[2] ? arg[2][0] : 0;
  a2=(a2-a3);
  a1=(a1*a2);
  a1=fabs(a1);
  a1=sq(a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void objN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void objN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int objN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int objN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* objN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* objN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int objN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* gi_fun:(i0[6],i1,i2[3],i3[2],i4[2x2])->(o0[6],o1) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[4] ? arg[4][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][5] : 0;
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3-a4);
  a4=(a2*a3);
  casadi_real a5=arg[4] ? arg[4][2] : 0;
  a5=sqrt(a5);
  casadi_real a6=arg[0] ? arg[0][3] : 0;
  casadi_real a7=arg[3] ? arg[3][1] : 0;
  a6=(a6-a7);
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a4+a4);
  a5=(a4*a5);
  a7=arg[4] ? arg[4][1] : 0;
  a7=sqrt(a7);
  a3=(a7*a3);
  casadi_real a8=arg[4] ? arg[4][3] : 0;
  a8=sqrt(a8);
  a6=(a8*a6);
  a3=(a3+a6);
  a3=(a3+a3);
  a8=(a3*a8);
  a5=(a5+a8);
  a5=(a1*a5);
  if (res[0]!=0) res[0][3]=a5;
  if (res[0]!=0) res[0][4]=a0;
  a4=(a4*a2);
  a3=(a3*a7);
  a4=(a4+a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][5]=a1;
  if (res[1]!=0) res[1][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int gi_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gi_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gi_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gi_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 9;
  return 0;
}

/* gN_fun:(i0[6],i1[3],i2,i3)->(o0[6]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[3] ? arg[3][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][3] : 0;
  casadi_real a4=arg[2] ? arg[2][0] : 0;
  a3=(a3-a4);
  a3=(a2*a3);
  a4=fabs(a3);
  a4=(a4+a4);
  a3=sign(a3);
  a3=(a3*a2);
  a4=(a4*a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int gN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}

/* Ji_fun:(i0[6],i1,i2[3],i3[2],i4[2x2])->(o0[2x6],o1[2]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  casadi_real a1=arg[4] ? arg[4][2] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][6]=a1;
  a1=arg[4] ? arg[4][3] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  a1=arg[4] ? arg[4][0] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][10]=a1;
  a1=arg[4] ? arg[4][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][11]=a1;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Ji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Ji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int Ji_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ji_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ji_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ji_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* JN_fun:(i0[6],i1[3],i2,i3)->(o0[1x6]) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=arg[3] ? arg[3][0] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f16(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void JN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void JN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int JN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int JN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* JN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* JN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int JN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* Ci_fun:(i0[6],i1,i2[3])->(o0[0x6],o1[0]) */
static int casadi_f17(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f17(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Ci_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ci_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Ci_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int Ci_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ci_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ci_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ci_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* CN_fun:(i0[6],i1[3])->(o0[0x6]) */
static int casadi_f18(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f18(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void CN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void CN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int CN_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int CN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* CN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* CN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int CN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* adj_fun:(i0[6],i1,i2[3],i3[2],i4[2x2],i5[6],i6[0])->(o0[7],o1[7],o2[7]) */
static int casadi_f19(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[4] ? arg[4][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][5] : 0;
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3-a4);
  a4=(a2*a3);
  casadi_real a5=arg[4] ? arg[4][2] : 0;
  a5=sqrt(a5);
  casadi_real a6=arg[0] ? arg[0][3] : 0;
  casadi_real a7=arg[3] ? arg[3][1] : 0;
  a6=(a6-a7);
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a4+a4);
  a5=(a4*a5);
  a7=arg[4] ? arg[4][1] : 0;
  a7=sqrt(a7);
  a3=(a7*a3);
  casadi_real a8=arg[4] ? arg[4][3] : 0;
  a8=sqrt(a8);
  a6=(a8*a6);
  a3=(a3+a6);
  a3=(a3+a3);
  a8=(a3*a8);
  a5=(a5+a8);
  a5=(a1*a5);
  if (res[0]!=0) res[0][3]=a5;
  if (res[0]!=0) res[0][4]=a0;
  a4=(a4*a2);
  a3=(a3*a7);
  a4=(a4+a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  a1=arg[0] ? arg[0][0] : 0;
  a4=(a1+a1);
  a3=1200000.;
  a7=arg[0] ? arg[0][1] : 0;
  a2=6.2500000000000000e+001;
  a5=1.2500000000000000e-003;
  a8=2.;
  a6=4.1666666666666669e-004;
  casadi_real a9=arg[5] ? arg[5][5] : 0;
  casadi_real a10=(a6*a9);
  casadi_real a11=(a8*a10);
  casadi_real a12=(a2*a11);
  casadi_real a13=-4.7619047619047616e-002;
  casadi_real a14=(a8*a10);
  casadi_real a15=(a13*a14);
  casadi_real a16=2.5000000000000001e-003;
  casadi_real a17=(a13*a10);
  casadi_real a18=(a6*a9);
  casadi_real a19=(a13*a18);
  casadi_real a20=arg[5] ? arg[5][4] : 0;
  a19=(a19+a20);
  casadi_real a21=(a13*a18);
  a20=(a6*a20);
  casadi_real a22=(a13*a20);
  a21=(a21+a22);
  a19=(a19+a21);
  a22=(a8*a18);
  casadi_real a23=(a13*a22);
  a21=(a16*a21);
  casadi_real a24=(a8*a20);
  a21=(a21+a24);
  a24=(a13*a21);
  a23=(a23+a24);
  a19=(a19+a23);
  a24=(a8*a18);
  casadi_real a25=(a13*a24);
  a23=(a5*a23);
  casadi_real a26=(a8*a20);
  a23=(a23+a26);
  a26=(a13*a23);
  a25=(a25+a26);
  a19=(a19+a25);
  a25=(a5*a25);
  a25=(a20+a25);
  a26=(a13*a25);
  a19=(a19+a26);
  a26=(a6*a19);
  casadi_real a27=(a13*a26);
  a17=(a17+a27);
  a27=(a16*a17);
  casadi_real a28=(a8*a26);
  a27=(a27+a28);
  a28=(a13*a27);
  a15=(a15+a28);
  a28=(a5*a15);
  casadi_real a29=(a8*a26);
  a28=(a28+a29);
  a29=(a2*a28);
  a12=(a12+a29);
  a29=(a5*a12);
  casadi_real a30=(a2*a18);
  casadi_real a31=(a2*a18);
  a20=(a2*a20);
  a31=(a31+a20);
  a30=(a30+a31);
  a20=(a2*a22);
  a21=(a2*a21);
  a20=(a20+a21);
  a30=(a30+a20);
  a21=(a2*a24);
  a23=(a2*a23);
  a21=(a21+a23);
  a30=(a30+a21);
  a25=(a2*a25);
  a30=(a30+a25);
  a25=arg[5] ? arg[5][2] : 0;
  a30=(a30+a25);
  a23=(a6*a30);
  a29=(a29+a23);
  casadi_real a32=(a2*a29);
  casadi_real a33=(a7*a32);
  a33=(a3*a33);
  a4=(a4*a33);
  a33=(a1+a1);
  casadi_real a34=2400000.;
  casadi_real a35=(a7*a32);
  a35=(a34*a35);
  a33=(a33*a35);
  a4=(a4+a33);
  a33=arg[2] ? arg[2][2] : 0;
  a35=20000.;
  casadi_real a36=(a5*a7);
  a36=(a1+a36);
  casadi_real a37=sq(a36);
  a37=(a35*a37);
  casadi_real a38=2000.;
  a37=(a37+a38);
  casadi_real a39=67.;
  a37=(a37/a39);
  casadi_real a40=sq(a1);
  a40=(a35*a40);
  a40=(a40+a38);
  a40=(a40/a39);
  casadi_real a41=(a40*a7);
  casadi_real a42=sq(a1);
  a42=(a3*a42);
  casadi_real a43=1000.;
  a42=(a42+a43);
  casadi_real a44=(a42*a1);
  a44=(a44/a39);
  a41=(a41+a44);
  a41=(a33-a41);
  a44=9.8100000000000005e+000;
  casadi_real a45=arg[2] ? arg[2][1] : 0;
  a44=(a44*a45);
  a41=(a41+a44);
  a45=(a5*a41);
  a45=(a7+a45);
  casadi_real a46=(a37*a45);
  casadi_real a47=sq(a36);
  a47=(a3*a47);
  a47=(a47+a43);
  casadi_real a48=(a47*a36);
  a48=(a48/a39);
  a46=(a46+a48);
  a46=(a33-a46);
  a46=(a46+a44);
  a48=(a5*a46);
  a48=(a7+a48);
  casadi_real a49=(a16*a48);
  a49=(a1+a49);
  casadi_real a50=(a49+a49);
  casadi_real a51=(a5*a45);
  a51=(a1+a51);
  casadi_real a52=sq(a51);
  a52=(a35*a52);
  a52=(a52+a38);
  a52=(a52/a39);
  casadi_real a53=(a52*a48);
  casadi_real a54=sq(a51);
  a54=(a3*a54);
  a54=(a54+a43);
  casadi_real a55=(a54*a51);
  a55=(a55/a39);
  a53=(a53+a55);
  a53=(a33-a53);
  a53=(a53+a44);
  a55=(a16*a53);
  a55=(a7+a55);
  casadi_real a56=(a2*a23);
  casadi_real a57=(a55*a56);
  a57=(a3*a57);
  a50=(a50*a57);
  a57=(a49+a49);
  casadi_real a58=(a55*a56);
  a58=(a34*a58);
  a57=(a57*a58);
  a50=(a50+a57);
  a57=sq(a49);
  a57=(a3*a57);
  a57=(a57+a43);
  a58=1.4925373134328358e-002;
  casadi_real a59=(a8*a45);
  a59=(a7+a59);
  casadi_real a60=(a8*a48);
  a59=(a59+a60);
  a59=(a59+a55);
  a59=(a6*a59);
  a59=(a1+a59);
  a60=sq(a59);
  a60=(a3*a60);
  a60=(a60+a43);
  a21=(a5*a21);
  a25=(a6*a25);
  a21=(a21+a25);
  casadi_real a61=(a2*a21);
  a60=(a60*a61);
  casadi_real a62=sq(a59);
  a62=(a34*a62);
  a62=(a62*a61);
  a60=(a60+a62);
  a62=arg[5] ? arg[5][1] : 0;
  a60=(a60+a62);
  a46=(a8*a46);
  a41=(a41+a46);
  a53=(a8*a53);
  a41=(a41+a53);
  a53=sq(a49);
  a53=(a35*a53);
  a53=(a53+a38);
  a53=(a53/a39);
  a46=(a53*a55);
  casadi_real a63=(a57*a49);
  a63=(a63/a39);
  a46=(a46+a63);
  a46=(a33-a46);
  a46=(a46+a44);
  a41=(a41+a46);
  a41=(a6*a41);
  a41=(a7+a41);
  a46=(a5*a41);
  a46=(a59+a46);
  a63=sq(a46);
  a63=(a35*a63);
  a63=(a63+a38);
  a63=(a63/a39);
  casadi_real a64=sq(a59);
  a64=(a35*a64);
  a64=(a64+a38);
  a64=(a64/a39);
  casadi_real a65=(a64*a41);
  casadi_real a66=sq(a59);
  a66=(a3*a66);
  a66=(a66+a43);
  casadi_real a67=(a66*a59);
  a67=(a67/a39);
  a65=(a65+a67);
  a65=(a33-a65);
  a65=(a65+a44);
  a65=(a5*a65);
  a65=(a41+a65);
  a67=(a63*a65);
  casadi_real a68=sq(a46);
  a68=(a3*a68);
  a68=(a68+a43);
  casadi_real a69=(a68*a46);
  a69=(a69/a39);
  a67=(a67+a69);
  a67=(a33-a67);
  a67=(a67+a44);
  a67=(a5*a67);
  a67=(a41+a67);
  a69=(a16*a67);
  a69=(a59+a69);
  casadi_real a70=sq(a69);
  a70=(a3*a70);
  a70=(a70+a43);
  casadi_real a71=(a2*a25);
  a70=(a70*a71);
  casadi_real a72=sq(a69);
  a72=(a34*a72);
  a72=(a72*a71);
  a70=(a70+a72);
  a72=sq(a69);
  a72=(a35*a72);
  a72=(a72+a38);
  a72=(a72/a39);
  a62=(a6*a62);
  a72=(a72*a62);
  a70=(a70-a72);
  a72=arg[5] ? arg[5][0] : 0;
  casadi_real a73=(a6*a72);
  a70=(a70+a73);
  a60=(a60+a70);
  casadi_real a74=(a5*a65);
  a74=(a59+a74);
  casadi_real a75=sq(a74);
  a75=(a3*a75);
  a75=(a75+a43);
  a31=(a16*a31);
  casadi_real a76=(a8*a25);
  a31=(a31+a76);
  a76=(a2*a31);
  a75=(a75*a76);
  casadi_real a77=sq(a74);
  a77=(a34*a77);
  a77=(a77*a76);
  a75=(a75+a77);
  a77=(a69+a69);
  casadi_real a78=sq(a74);
  a78=(a35*a78);
  a78=(a78+a38);
  a78=(a78/a39);
  a38=(a78*a67);
  casadi_real a79=sq(a74);
  a79=(a3*a79);
  a79=(a79+a43);
  casadi_real a80=(a79*a74);
  a80=(a80/a39);
  a38=(a38+a80);
  a33=(a33-a38);
  a33=(a33+a44);
  a33=(a16*a33);
  a33=(a41+a33);
  a44=(a33*a71);
  a44=(a3*a44);
  a77=(a77*a44);
  a44=(a69+a69);
  a71=(a33*a71);
  a71=(a34*a71);
  a44=(a44*a71);
  a77=(a77+a44);
  a44=sq(a69);
  a44=(a3*a44);
  a44=(a44+a43);
  a71=(a58*a62);
  a44=(a44*a71);
  a77=(a77-a44);
  a44=(a69+a69);
  a71=(a69*a71);
  a71=(a3*a71);
  a44=(a44*a71);
  a77=(a77-a44);
  a69=(a69+a69);
  a33=(a33*a62);
  a33=(a58*a33);
  a33=(a35*a33);
  a69=(a69*a33);
  a77=(a77-a69);
  a69=(a16*a77);
  a75=(a75+a69);
  a69=(a8*a62);
  a70=(a16*a70);
  a69=(a69+a70);
  a78=(a78*a69);
  a75=(a75-a78);
  a78=(a8*a73);
  a75=(a75+a78);
  a60=(a60+a75);
  a78=(a46+a46);
  a20=(a5*a20);
  a70=(a8*a25);
  a20=(a20+a70);
  a70=(a2*a20);
  a33=(a65*a70);
  a33=(a3*a33);
  a78=(a78*a33);
  a33=(a46+a46);
  a44=(a65*a70);
  a44=(a34*a44);
  a33=(a33*a44);
  a78=(a78+a33);
  a33=(a8*a62);
  a75=(a5*a75);
  a33=(a33+a75);
  a75=(a58*a33);
  a68=(a68*a75);
  a78=(a78-a68);
  a68=(a46+a46);
  a75=(a46*a75);
  a75=(a3*a75);
  a68=(a68*a75);
  a78=(a78-a68);
  a68=(a46+a46);
  a65=(a65*a33);
  a65=(a58*a65);
  a65=(a35*a65);
  a68=(a68*a65);
  a78=(a78-a68);
  a68=(a5*a78);
  a60=(a60+a68);
  a60=(a60+a73);
  a68=sq(a46);
  a68=(a3*a68);
  a68=(a68+a43);
  a68=(a68*a70);
  a46=sq(a46);
  a46=(a34*a46);
  a46=(a46*a70);
  a68=(a68+a46);
  a46=(a74+a74);
  a70=(a67*a76);
  a70=(a3*a70);
  a46=(a46*a70);
  a70=(a74+a74);
  a76=(a67*a76);
  a76=(a34*a76);
  a70=(a70*a76);
  a46=(a46+a70);
  a70=(a58*a69);
  a79=(a79*a70);
  a46=(a46-a79);
  a79=(a74+a74);
  a70=(a74*a70);
  a70=(a3*a70);
  a79=(a79*a70);
  a46=(a46-a79);
  a74=(a74+a74);
  a67=(a67*a69);
  a67=(a58*a67);
  a67=(a35*a67);
  a74=(a74*a67);
  a46=(a46-a74);
  a74=(a5*a46);
  a68=(a68+a74);
  a63=(a63*a33);
  a68=(a68-a63);
  a73=(a8*a73);
  a68=(a68+a73);
  a60=(a60+a68);
  a68=(a5*a68);
  a62=(a62+a68);
  a64=(a64*a62);
  a60=(a60-a64);
  a64=(a6*a60);
  a68=(a58*a64);
  a57=(a57*a68);
  a50=(a50-a57);
  a57=(a49+a49);
  a68=(a49*a68);
  a68=(a3*a68);
  a57=(a57*a68);
  a50=(a50-a57);
  a57=(a49+a49);
  a55=(a55*a64);
  a55=(a58*a55);
  a55=(a35*a55);
  a57=(a57*a55);
  a50=(a50-a57);
  a4=(a4+a50);
  a57=(a59+a59);
  a55=(a41*a61);
  a55=(a3*a55);
  a57=(a57*a55);
  a55=(a59+a59);
  a61=(a41*a61);
  a61=(a34*a61);
  a55=(a55*a61);
  a57=(a57+a55);
  a57=(a57+a77);
  a57=(a57+a72);
  a57=(a57+a46);
  a57=(a57+a78);
  a78=(a58*a62);
  a66=(a66*a78);
  a57=(a57-a66);
  a66=(a59+a59);
  a78=(a59*a78);
  a78=(a3*a78);
  a66=(a66*a78);
  a57=(a57-a66);
  a59=(a59+a59);
  a41=(a41*a62);
  a41=(a58*a41);
  a41=(a35*a41);
  a59=(a59*a41);
  a57=(a57-a59);
  a4=(a4+a57);
  a59=(a51+a51);
  a41=(a2*a10);
  a62=(a2*a26);
  a41=(a41+a62);
  a62=(a16*a41);
  a66=(a8*a23);
  a62=(a62+a66);
  a66=(a2*a62);
  a78=(a48*a66);
  a78=(a3*a78);
  a59=(a59*a78);
  a78=(a51+a51);
  a46=(a48*a66);
  a46=(a34*a46);
  a78=(a78*a46);
  a59=(a59+a78);
  a78=(a8*a64);
  a46=sq(a49);
  a46=(a3*a46);
  a46=(a46+a43);
  a46=(a46*a56);
  a49=sq(a49);
  a49=(a34*a49);
  a49=(a49*a56);
  a46=(a46+a49);
  a53=(a53*a64);
  a46=(a46-a53);
  a57=(a6*a57);
  a46=(a46+a57);
  a53=(a16*a46);
  a78=(a78+a53);
  a53=(a58*a78);
  a54=(a54*a53);
  a59=(a59-a54);
  a54=(a51+a51);
  a53=(a51*a53);
  a53=(a3*a53);
  a54=(a54*a53);
  a59=(a59-a54);
  a54=(a51+a51);
  a48=(a48*a78);
  a48=(a58*a48);
  a48=(a35*a48);
  a54=(a54*a48);
  a59=(a59-a54);
  a4=(a4+a59);
  a54=(a36+a36);
  a48=(a2*a14);
  a27=(a2*a27);
  a48=(a48+a27);
  a27=(a5*a48);
  a53=(a8*a23);
  a27=(a27+a53);
  a53=(a2*a27);
  a49=(a45*a53);
  a49=(a3*a49);
  a54=(a54*a49);
  a49=(a36+a36);
  a56=(a45*a53);
  a56=(a34*a56);
  a49=(a49*a56);
  a54=(a54+a49);
  a49=(a8*a64);
  a56=sq(a51);
  a56=(a3*a56);
  a56=(a56+a43);
  a56=(a56*a66);
  a51=sq(a51);
  a51=(a34*a51);
  a51=(a51*a66);
  a56=(a56+a51);
  a50=(a16*a50);
  a56=(a56+a50);
  a52=(a52*a78);
  a56=(a56-a52);
  a52=(a8*a57);
  a56=(a56+a52);
  a52=(a5*a56);
  a49=(a49+a52);
  a52=(a58*a49);
  a47=(a47*a52);
  a54=(a54-a47);
  a47=(a36+a36);
  a52=(a36*a52);
  a52=(a3*a52);
  a47=(a47*a52);
  a54=(a54-a47);
  a47=(a36+a36);
  a45=(a45*a49);
  a45=(a58*a45);
  a45=(a35*a45);
  a47=(a47*a45);
  a54=(a54-a47);
  a4=(a4+a54);
  a47=sq(a36);
  a47=(a3*a47);
  a47=(a47+a43);
  a47=(a47*a53);
  a36=sq(a36);
  a36=(a34*a36);
  a36=(a36*a53);
  a47=(a47+a36);
  a59=(a5*a59);
  a47=(a47+a59);
  a37=(a37*a49);
  a47=(a47-a37);
  a37=(a8*a57);
  a47=(a47+a37);
  a37=(a5*a47);
  a64=(a64+a37);
  a37=(a58*a64);
  a42=(a42*a37);
  a4=(a4-a42);
  a42=(a1+a1);
  a37=(a1*a37);
  a37=(a3*a37);
  a42=(a42*a37);
  a4=(a4-a42);
  a42=(a1+a1);
  a7=(a7*a64);
  a58=(a58*a7);
  a35=(a35*a58);
  a42=(a42*a35);
  a4=(a4-a42);
  if (res[1]!=0) res[1][0]=a4;
  a4=sq(a1);
  a3=(a3*a4);
  a3=(a3+a43);
  a3=(a3*a32);
  a1=sq(a1);
  a34=(a34*a1);
  a34=(a34*a32);
  a3=(a3+a34);
  a3=(a3+a60);
  a3=(a3+a46);
  a3=(a3+a56);
  a54=(a5*a54);
  a3=(a3+a54);
  a3=(a3+a57);
  a3=(a3+a47);
  a40=(a40*a64);
  a3=(a3-a40);
  if (res[1]!=0) res[1][1]=a3;
  a3=(a2*a10);
  a3=(a3+a41);
  a3=(a3+a48);
  a3=(a3+a12);
  a12=(a13*a11);
  a28=(a13*a28);
  a12=(a12+a28);
  a28=(a5*a12);
  a26=(a26+a28);
  a2=(a2*a26);
  a3=(a3+a2);
  a3=(a3+a30);
  if (res[1]!=0) res[1][2]=a3;
  a3=(a10+a14);
  a3=(a3+a11);
  a3=(a3+a10);
  a30=(a18+a22);
  a30=(a30+a24);
  a30=(a30+a18);
  a2=arg[5] ? arg[5][3] : 0;
  a30=(a30+a2);
  a3=(a3+a30);
  if (res[1]!=0) res[1][3]=a3;
  a3=(a13*a10);
  a3=(a3+a19);
  a3=(a3+a17);
  a3=(a3+a15);
  a3=(a3+a12);
  a13=(a13*a26);
  a3=(a3+a13);
  if (res[1]!=0) res[1][4]=a3;
  if (res[1]!=0) res[1][5]=a9;
  a18=(a16*a18);
  a22=(a5*a22);
  a18=(a18+a22);
  a24=(a5*a24);
  a18=(a18+a24);
  a16=(a16*a10);
  a18=(a18+a16);
  a14=(a5*a14);
  a18=(a18+a14);
  a5=(a5*a11);
  a18=(a18+a5);
  a2=(a6*a2);
  a18=(a18+a2);
  a5=(a8*a2);
  a18=(a18+a5);
  a18=(a18+a2);
  a2=(a8*a2);
  a18=(a18+a2);
  a6=(a6*a30);
  a18=(a18+a6);
  a30=(a8*a6);
  a18=(a18+a30);
  a18=(a18+a6);
  a8=(a8*a6);
  a18=(a18+a8);
  a18=(a18+a25);
  a18=(a18+a31);
  a18=(a18+a20);
  a18=(a18+a21);
  a18=(a18+a23);
  a18=(a18+a62);
  a18=(a18+a27);
  a18=(a18+a29);
  if (res[1]!=0) res[1][6]=a18;
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  if (res[2]!=0) res[2][3]=a0;
  if (res[2]!=0) res[2][4]=a0;
  if (res[2]!=0) res[2][5]=a0;
  if (res[2]!=0) res[2][6]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f19(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adj_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adj_fun_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT int adj_fun_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    case 5: return casadi_s0;
    case 6: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s11;
    case 2: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 81;
  return 0;
}

/* adjN_fun:(i0[6],i1[3],i2,i3,i4[0])->(o0[6],o1[6]) */
static int casadi_f20(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[3] ? arg[3][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][3] : 0;
  casadi_real a4=arg[2] ? arg[2][0] : 0;
  a3=(a3-a4);
  a3=(a2*a3);
  a4=fabs(a3);
  a4=(a4+a4);
  a3=sign(a3);
  a3=(a3*a2);
  a4=(a4*a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f20(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adjN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adjN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adjN_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int adjN_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adjN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
