/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_src_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f17 CASADI_PREFIX(f17)
#define casadi_f18 CASADI_PREFIX(f18)
#define casadi_f19 CASADI_PREFIX(f19)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f20 CASADI_PREFIX(f20)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const int casadi_s1[5] = {1, 1, 0, 1, 0};
static const int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const int casadi_s3[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const int casadi_s5[3] = {0, 0, 0};
static const int casadi_s6[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const int casadi_s7[15] = {2, 4, 0, 2, 4, 6, 8, 0, 1, 0, 1, 0, 1, 0, 1};
static const int casadi_s8[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const int casadi_s9[7] = {0, 4, 0, 0, 0, 0, 0};
static const int casadi_s10[4] = {0, 1, 0, 0};
static const int casadi_s11[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* f_fun:(states[4],controls,params[3])->(xdot[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[2] ? arg[2][2] : 0;
  casadi_real a2=200.;
  casadi_real a3=10.;
  casadi_real a4=arg[0] ? arg[0][0] : 0;
  casadi_real a5=(a3*a4);
  a5=sq(a5);
  a2=(a2*a5);
  a5=2000.;
  a2=(a2+a5);
  a5=67.;
  a2=(a2/a5);
  a2=(a2*a0);
  casadi_real a6=12000.;
  a3=(a3*a4);
  a3=sq(a3);
  a6=(a6*a3);
  a3=1000.;
  a6=(a6+a3);
  a6=(a6*a4);
  a6=(a6/a5);
  a2=(a2+a6);
  a1=(a1-a2);
  a2=9.8100000000000005e+000;
  a6=arg[2] ? arg[2][1] : 0;
  a2=(a2*a6);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=2400000.;
  a1=(a1*a4);
  a1=(a1*a0);
  a2=1200000.;
  a4=sq(a4);
  a2=(a2*a4);
  a2=(a2+a3);
  a2=(a2*a0);
  a1=(a1+a2);
  a2=arg[1] ? arg[1][0] : 0;
  a1=(a1+a2);
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int f_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* f_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_out(int i){
  switch (i) {
    case 0: return "xdot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 7;
  return 0;
}

/* vdeFun:(i0[4],i1,i2[3],i3[4x4],i4[4])->(o0[4x4],o1[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[3] ? arg[3][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  casadi_real a2=1.4925373134328358e-002;
  casadi_real a3=200.;
  casadi_real a4=10.;
  casadi_real a5=arg[0] ? arg[0][0] : 0;
  casadi_real a6=(a4*a5);
  casadi_real a7=(a6+a6);
  casadi_real a8=arg[3] ? arg[3][0] : 0;
  casadi_real a9=(a4*a8);
  a9=(a7*a9);
  a9=(a3*a9);
  a9=(a2*a9);
  a9=(a1*a9);
  casadi_real a10=sq(a6);
  a10=(a3*a10);
  casadi_real a11=2000.;
  a10=(a10+a11);
  a11=67.;
  a10=(a10/a11);
  a11=(a10*a0);
  a9=(a9+a11);
  a11=12000.;
  casadi_real a12=(a4*a5);
  casadi_real a13=(a12+a12);
  casadi_real a14=(a4*a8);
  a14=(a13*a14);
  a14=(a11*a14);
  a14=(a5*a14);
  casadi_real a15=sq(a12);
  a15=(a11*a15);
  casadi_real a16=1000.;
  a15=(a15+a16);
  casadi_real a17=(a15*a8);
  a14=(a14+a17);
  a14=(a2*a14);
  a9=(a9+a14);
  a9=(-a9);
  if (res[0]!=0) res[0][1]=a9;
  a9=2400000.;
  a14=(a9*a8);
  a14=(a1*a14);
  a17=(a9*a5);
  casadi_real a18=(a17*a0);
  a14=(a14+a18);
  a18=1200000.;
  casadi_real a19=(a5+a5);
  a8=(a19*a8);
  a8=(a18*a8);
  a8=(a1*a8);
  casadi_real a20=sq(a5);
  a20=(a18*a20);
  a20=(a20+a16);
  a0=(a20*a0);
  a8=(a8+a0);
  a14=(a14+a8);
  if (res[0]!=0) res[0][2]=a14;
  a14=0.;
  if (res[0]!=0) res[0][3]=a14;
  a8=arg[3] ? arg[3][5] : 0;
  if (res[0]!=0) res[0][4]=a8;
  a0=arg[3] ? arg[3][4] : 0;
  a16=(a4*a0);
  a16=(a7*a16);
  a16=(a3*a16);
  a16=(a2*a16);
  a16=(a1*a16);
  casadi_real a21=(a10*a8);
  a16=(a16+a21);
  a21=(a4*a0);
  a21=(a13*a21);
  a21=(a11*a21);
  a21=(a5*a21);
  casadi_real a22=(a15*a0);
  a21=(a21+a22);
  a21=(a2*a21);
  a16=(a16+a21);
  a16=(-a16);
  if (res[0]!=0) res[0][5]=a16;
  a16=(a9*a0);
  a16=(a1*a16);
  a21=(a17*a8);
  a16=(a16+a21);
  a0=(a19*a0);
  a0=(a18*a0);
  a0=(a1*a0);
  a8=(a20*a8);
  a0=(a0+a8);
  a16=(a16+a0);
  if (res[0]!=0) res[0][6]=a16;
  if (res[0]!=0) res[0][7]=a14;
  a16=arg[3] ? arg[3][9] : 0;
  if (res[0]!=0) res[0][8]=a16;
  a0=arg[3] ? arg[3][8] : 0;
  a8=(a4*a0);
  a8=(a7*a8);
  a8=(a3*a8);
  a8=(a2*a8);
  a8=(a1*a8);
  a21=(a10*a16);
  a8=(a8+a21);
  a21=(a4*a0);
  a21=(a13*a21);
  a21=(a11*a21);
  a21=(a5*a21);
  a22=(a15*a0);
  a21=(a21+a22);
  a21=(a2*a21);
  a8=(a8+a21);
  a8=(-a8);
  if (res[0]!=0) res[0][9]=a8;
  a8=(a9*a0);
  a8=(a1*a8);
  a21=(a17*a16);
  a8=(a8+a21);
  a0=(a19*a0);
  a0=(a18*a0);
  a0=(a1*a0);
  a16=(a20*a16);
  a0=(a0+a16);
  a8=(a8+a0);
  if (res[0]!=0) res[0][10]=a8;
  if (res[0]!=0) res[0][11]=a14;
  a8=arg[3] ? arg[3][13] : 0;
  if (res[0]!=0) res[0][12]=a8;
  a0=arg[3] ? arg[3][12] : 0;
  a16=(a4*a0);
  a7=(a7*a16);
  a7=(a3*a7);
  a7=(a2*a7);
  a7=(a1*a7);
  a16=(a10*a8);
  a7=(a7+a16);
  a16=(a4*a0);
  a13=(a13*a16);
  a13=(a11*a13);
  a13=(a5*a13);
  a16=(a15*a0);
  a13=(a13+a16);
  a13=(a2*a13);
  a7=(a7+a13);
  a7=(-a7);
  if (res[0]!=0) res[0][13]=a7;
  a7=(a9*a0);
  a7=(a1*a7);
  a13=(a17*a8);
  a7=(a7+a13);
  a19=(a19*a0);
  a19=(a18*a19);
  a19=(a1*a19);
  a8=(a20*a8);
  a19=(a19+a8);
  a7=(a7+a19);
  if (res[0]!=0) res[0][14]=a7;
  if (res[0]!=0) res[0][15]=a14;
  a14=arg[4] ? arg[4][1] : 0;
  if (res[1]!=0) res[1][0]=a14;
  a6=(a6+a6);
  a7=arg[4] ? arg[4][0] : 0;
  a19=(a4*a7);
  a6=(a6*a19);
  a3=(a3*a6);
  a3=(a2*a3);
  a3=(a1*a3);
  a10=(a10*a14);
  a3=(a3+a10);
  a12=(a12+a12);
  a4=(a4*a7);
  a12=(a12*a4);
  a11=(a11*a12);
  a11=(a5*a11);
  a15=(a15*a7);
  a11=(a11+a15);
  a2=(a2*a11);
  a3=(a3+a2);
  a3=(-a3);
  if (res[1]!=0) res[1][1]=a3;
  a3=1.;
  a9=(a9*a7);
  a9=(a1*a9);
  a17=(a17*a14);
  a9=(a9+a17);
  a5=(a5+a5);
  a5=(a5*a7);
  a18=(a18*a5);
  a1=(a1*a18);
  a20=(a20*a14);
  a1=(a1+a20);
  a9=(a9+a1);
  a9=(a3+a9);
  if (res[1]!=0) res[1][2]=a9;
  if (res[1]!=0) res[1][3]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void vdeFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void vdeFun_decref(void) {
}

CASADI_SYMBOL_EXPORT int vdeFun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int vdeFun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* vdeFun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* vdeFun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int vdeFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 23;
  return 0;
}

/* impl_f_fun:(i0[4],i1,i2[3],i3[4])->(o0[4]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[3] ? arg[3][0] : 0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3] ? arg[3][1] : 0;
  casadi_real a2=arg[2] ? arg[2][2] : 0;
  casadi_real a3=200.;
  casadi_real a4=10.;
  casadi_real a5=arg[0] ? arg[0][0] : 0;
  casadi_real a6=(a4*a5);
  a6=sq(a6);
  a3=(a3*a6);
  a6=2000.;
  a3=(a3+a6);
  a6=67.;
  a3=(a3/a6);
  a3=(a3*a1);
  casadi_real a7=12000.;
  a4=(a4*a5);
  a4=sq(a4);
  a7=(a7*a4);
  a4=1000.;
  a7=(a7+a4);
  a7=(a7*a5);
  a7=(a7/a6);
  a3=(a3+a7);
  a2=(a2-a3);
  a3=9.8100000000000005e+000;
  a7=arg[2] ? arg[2][1] : 0;
  a3=(a3*a7);
  a2=(a2+a3);
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3] ? arg[3][2] : 0;
  a2=2400000.;
  a2=(a2*a5);
  a2=(a2*a1);
  a3=1200000.;
  a5=sq(a5);
  a3=(a3*a5);
  a3=(a3+a4);
  a3=(a3*a1);
  a2=(a2+a3);
  a3=arg[1] ? arg[1][0] : 0;
  a2=(a2+a3);
  a0=(a0-a2);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3] ? arg[3][3] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_f_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 8;
  return 0;
}

/* impl_jac_x_fun:(i0[4],i1,i2[3],i3[4])->(o0[4x4]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  casadi_real a2=1.4925373134328358e-002;
  casadi_real a3=200.;
  casadi_real a4=10.;
  casadi_real a5=arg[0] ? arg[0][0] : 0;
  casadi_real a6=(a4*a5);
  casadi_real a7=(a6+a6);
  a7=(a4*a7);
  a7=(a3*a7);
  a7=(a2*a7);
  a7=(a1*a7);
  casadi_real a8=12000.;
  casadi_real a9=(a4*a5);
  casadi_real a10=(a9+a9);
  a4=(a4*a10);
  a4=(a8*a4);
  a4=(a5*a4);
  a9=sq(a9);
  a8=(a8*a9);
  a9=1000.;
  a8=(a8+a9);
  a4=(a4+a8);
  a2=(a2*a4);
  a7=(a7+a2);
  if (res[0]!=0) res[0][1]=a7;
  a7=2400000.;
  a2=(a7*a1);
  a4=1200000.;
  a8=(a5+a5);
  a8=(a4*a8);
  a1=(a1*a8);
  a2=(a2+a1);
  a2=(-a2);
  if (res[0]!=0) res[0][2]=a2;
  if (res[0]!=0) res[0][3]=a0;
  a2=-1.;
  if (res[0]!=0) res[0][4]=a2;
  a6=sq(a6);
  a3=(a3*a6);
  a6=2000.;
  a3=(a3+a6);
  a6=67.;
  a3=(a3/a6);
  if (res[0]!=0) res[0][5]=a3;
  a7=(a7*a5);
  a5=sq(a5);
  a4=(a4*a5);
  a4=(a4+a9);
  a7=(a7+a4);
  a7=(-a7);
  if (res[0]!=0) res[0][6]=a7;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_x_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_x_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_x_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_x_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 11;
  return 0;
}

/* impl_jac_u_fun:(i0[4],i1,i2[3],i3[4])->(o0[4]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=-1.;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_u_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_u_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_u_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_u_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* impl_jac_xdot_fun:(i0[4],i1,i2[3],i3[4])->(o0[4x4]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_xdot_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_xdot_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_xdot_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_xdot_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_xdot_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_xdot_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* F:(i0[4],i1,i2[3])->(o0[4]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][0] : 0;
  casadi_real a1=4.1666666666666669e-004;
  casadi_real a2=arg[0] ? arg[0][1] : 0;
  casadi_real a3=2.;
  casadi_real a4=1.2500000000000000e-003;
  casadi_real a5=arg[2] ? arg[2][2] : 0;
  casadi_real a6=200.;
  casadi_real a7=10.;
  casadi_real a8=(a7*a0);
  a8=sq(a8);
  a8=(a6*a8);
  casadi_real a9=2000.;
  a8=(a8+a9);
  casadi_real a10=67.;
  a8=(a8/a10);
  a8=(a8*a2);
  casadi_real a11=12000.;
  casadi_real a12=(a7*a0);
  a12=sq(a12);
  a12=(a11*a12);
  casadi_real a13=1000.;
  a12=(a12+a13);
  a12=(a12*a0);
  a12=(a12/a10);
  a8=(a8+a12);
  a8=(a5-a8);
  a12=9.8100000000000005e+000;
  casadi_real a14=arg[2] ? arg[2][1] : 0;
  a12=(a12*a14);
  a8=(a8+a12);
  a14=(a4*a8);
  a14=(a2+a14);
  casadi_real a15=(a3*a14);
  a15=(a2+a15);
  casadi_real a16=(a4*a2);
  a16=(a0+a16);
  casadi_real a17=(a7*a16);
  a17=sq(a17);
  a17=(a6*a17);
  a17=(a17+a9);
  a17=(a17/a10);
  a17=(a17*a14);
  casadi_real a18=(a7*a16);
  a18=sq(a18);
  a18=(a11*a18);
  a18=(a18+a13);
  a18=(a18*a16);
  a18=(a18/a10);
  a17=(a17+a18);
  a17=(a5-a17);
  a17=(a17+a12);
  a18=(a4*a17);
  a18=(a2+a18);
  casadi_real a19=(a3*a18);
  a15=(a15+a19);
  a19=2.5000000000000001e-003;
  casadi_real a20=(a4*a14);
  a20=(a0+a20);
  casadi_real a21=(a7*a20);
  a21=sq(a21);
  a21=(a6*a21);
  a21=(a21+a9);
  a21=(a21/a10);
  a21=(a21*a18);
  casadi_real a22=(a7*a20);
  a22=sq(a22);
  a22=(a11*a22);
  a22=(a22+a13);
  a22=(a22*a20);
  a22=(a22/a10);
  a21=(a21+a22);
  a21=(a5-a21);
  a21=(a21+a12);
  a22=(a19*a21);
  a22=(a2+a22);
  a15=(a15+a22);
  a15=(a1*a15);
  a15=(a0+a15);
  a17=(a3*a17);
  a8=(a8+a17);
  a21=(a3*a21);
  a8=(a8+a21);
  a21=(a19*a18);
  a21=(a0+a21);
  a17=(a7*a21);
  a17=sq(a17);
  a17=(a6*a17);
  a17=(a17+a9);
  a17=(a17/a10);
  a17=(a17*a22);
  casadi_real a23=(a7*a21);
  a23=sq(a23);
  a23=(a11*a23);
  a23=(a23+a13);
  a23=(a23*a21);
  a23=(a23/a10);
  a17=(a17+a23);
  a17=(a5-a17);
  a17=(a17+a12);
  a8=(a8+a17);
  a8=(a1*a8);
  a8=(a2+a8);
  a17=(a7*a15);
  a17=sq(a17);
  a17=(a6*a17);
  a17=(a17+a9);
  a17=(a17/a10);
  a17=(a17*a8);
  a23=(a7*a15);
  a23=sq(a23);
  a23=(a11*a23);
  a23=(a23+a13);
  a23=(a23*a15);
  a23=(a23/a10);
  a17=(a17+a23);
  a17=(a5-a17);
  a17=(a17+a12);
  a23=(a4*a17);
  a23=(a8+a23);
  casadi_real a24=(a3*a23);
  a24=(a8+a24);
  casadi_real a25=(a4*a8);
  a25=(a15+a25);
  casadi_real a26=(a7*a25);
  a26=sq(a26);
  a26=(a6*a26);
  a26=(a26+a9);
  a26=(a26/a10);
  a26=(a26*a23);
  casadi_real a27=(a7*a25);
  a27=sq(a27);
  a27=(a11*a27);
  a27=(a27+a13);
  a27=(a27*a25);
  a27=(a27/a10);
  a26=(a26+a27);
  a26=(a5-a26);
  a26=(a26+a12);
  a27=(a4*a26);
  a27=(a8+a27);
  casadi_real a28=(a3*a27);
  a24=(a24+a28);
  a4=(a4*a23);
  a4=(a15+a4);
  a28=(a7*a4);
  a28=sq(a28);
  a28=(a6*a28);
  a28=(a28+a9);
  a28=(a28/a10);
  a28=(a28*a27);
  casadi_real a29=(a7*a4);
  a29=sq(a29);
  a29=(a11*a29);
  a29=(a29+a13);
  a29=(a29*a4);
  a29=(a29/a10);
  a28=(a28+a29);
  a28=(a5-a28);
  a28=(a28+a12);
  a29=(a19*a28);
  a29=(a8+a29);
  a24=(a24+a29);
  a24=(a1*a24);
  a24=(a15+a24);
  if (res[0]!=0) res[0][0]=a24;
  a26=(a3*a26);
  a17=(a17+a26);
  a28=(a3*a28);
  a17=(a17+a28);
  a19=(a19*a27);
  a19=(a15+a19);
  a28=(a7*a19);
  a28=sq(a28);
  a6=(a6*a28);
  a6=(a6+a9);
  a6=(a6/a10);
  a6=(a6*a29);
  a7=(a7*a19);
  a7=sq(a7);
  a11=(a11*a7);
  a11=(a11+a13);
  a11=(a11*a19);
  a11=(a11/a10);
  a6=(a6+a11);
  a5=(a5-a6);
  a5=(a5+a12);
  a17=(a17+a5);
  a17=(a1*a17);
  a17=(a8+a17);
  if (res[0]!=0) res[0][1]=a17;
  a17=arg[0] ? arg[0][2] : 0;
  a5=2400000.;
  a12=(a5*a0);
  a12=(a12*a2);
  a6=1200000.;
  a0=sq(a0);
  a0=(a6*a0);
  a0=(a0+a13);
  a0=(a0*a2);
  a12=(a12+a0);
  a0=arg[1] ? arg[1][0] : 0;
  a12=(a12+a0);
  a2=(a5*a16);
  a2=(a2*a14);
  a16=sq(a16);
  a16=(a6*a16);
  a16=(a16+a13);
  a16=(a16*a14);
  a2=(a2+a16);
  a2=(a2+a0);
  a2=(a3*a2);
  a12=(a12+a2);
  a2=(a5*a20);
  a2=(a2*a18);
  a20=sq(a20);
  a20=(a6*a20);
  a20=(a20+a13);
  a20=(a20*a18);
  a2=(a2+a20);
  a2=(a2+a0);
  a2=(a3*a2);
  a12=(a12+a2);
  a2=(a5*a21);
  a2=(a2*a22);
  a21=sq(a21);
  a21=(a6*a21);
  a21=(a21+a13);
  a21=(a21*a22);
  a2=(a2+a21);
  a2=(a2+a0);
  a12=(a12+a2);
  a12=(a1*a12);
  a17=(a17+a12);
  a12=(a5*a15);
  a12=(a12*a8);
  a15=sq(a15);
  a15=(a6*a15);
  a15=(a15+a13);
  a15=(a15*a8);
  a12=(a12+a15);
  a12=(a12+a0);
  a15=(a5*a25);
  a15=(a15*a23);
  a25=sq(a25);
  a25=(a6*a25);
  a25=(a25+a13);
  a25=(a25*a23);
  a15=(a15+a25);
  a15=(a15+a0);
  a15=(a3*a15);
  a12=(a12+a15);
  a15=(a5*a4);
  a15=(a15*a27);
  a4=sq(a4);
  a4=(a6*a4);
  a4=(a4+a13);
  a4=(a4*a27);
  a15=(a15+a4);
  a15=(a15+a0);
  a15=(a3*a15);
  a12=(a12+a15);
  a5=(a5*a19);
  a5=(a5*a29);
  a19=sq(a19);
  a6=(a6*a19);
  a6=(a6+a13);
  a6=(a6*a29);
  a5=(a5+a6);
  a5=(a5+a0);
  a12=(a12+a5);
  a12=(a1*a12);
  a17=(a17+a12);
  if (res[0]!=0) res[0][2]=a17;
  a17=arg[0] ? arg[0][3] : 0;
  a12=(a3*a0);
  a12=(a0+a12);
  a5=(a3*a0);
  a12=(a12+a5);
  a12=(a12+a0);
  a12=(a1*a12);
  a17=(a17+a12);
  a12=(a3*a0);
  a12=(a0+a12);
  a3=(a3*a0);
  a12=(a12+a3);
  a12=(a12+a0);
  a1=(a1*a12);
  a17=(a17+a1);
  if (res[0]!=0) res[0][3]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int F(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void F_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_decref(void) {
}

CASADI_SYMBOL_EXPORT int F_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* F_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* F_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* F_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 30;
  return 0;
}

/* D:(i0[4],i1,i2[3])->(o0[4x4],o1[4]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  casadi_real a1=4.1666666666666669e-004;
  casadi_real a2=2.;
  casadi_real a3=1.2500000000000000e-003;
  casadi_real a4=arg[0] ? arg[0][1] : 0;
  casadi_real a5=1.4925373134328358e-002;
  casadi_real a6=200.;
  casadi_real a7=10.;
  casadi_real a8=arg[0] ? arg[0][0] : 0;
  casadi_real a9=(a7*a8);
  casadi_real a10=(a9+a9);
  a10=(a7*a10);
  a10=(a6*a10);
  a10=(a5*a10);
  a10=(a4*a10);
  casadi_real a11=12000.;
  casadi_real a12=(a7*a8);
  casadi_real a13=(a12+a12);
  a13=(a7*a13);
  a13=(a11*a13);
  a13=(a8*a13);
  a12=sq(a12);
  a12=(a11*a12);
  casadi_real a14=1000.;
  a12=(a12+a14);
  a13=(a13+a12);
  a13=(a5*a13);
  a10=(a10+a13);
  a13=(a3*a10);
  casadi_real a15=(a2*a13);
  casadi_real a16=arg[2] ? arg[2][2] : 0;
  a9=sq(a9);
  a9=(a6*a9);
  casadi_real a17=2000.;
  a9=(a9+a17);
  casadi_real a18=67.;
  a9=(a9/a18);
  casadi_real a19=(a9*a4);
  a12=(a12*a8);
  a12=(a12/a18);
  a19=(a19+a12);
  a19=(a16-a19);
  a12=9.8100000000000005e+000;
  casadi_real a20=arg[2] ? arg[2][1] : 0;
  a12=(a12*a20);
  a19=(a19+a12);
  a20=(a3*a19);
  a20=(a4+a20);
  casadi_real a21=(a3*a4);
  a21=(a8+a21);
  casadi_real a22=(a7*a21);
  casadi_real a23=(a22+a22);
  casadi_real a24=(a7*a23);
  a24=(a6*a24);
  a24=(a5*a24);
  a24=(a20*a24);
  a22=sq(a22);
  a22=(a6*a22);
  a22=(a22+a17);
  a22=(a22/a18);
  casadi_real a25=(a22*a13);
  a24=(a24-a25);
  a25=(a7*a21);
  casadi_real a26=(a25+a25);
  casadi_real a27=(a7*a26);
  a27=(a11*a27);
  a27=(a21*a27);
  a25=sq(a25);
  a25=(a11*a25);
  a25=(a25+a14);
  a27=(a27+a25);
  a27=(a5*a27);
  a24=(a24+a27);
  a27=(a3*a24);
  casadi_real a28=(a2*a27);
  a15=(a15+a28);
  a28=2.5000000000000001e-003;
  casadi_real a29=(a22*a20);
  casadi_real a30=(a25*a21);
  a30=(a30/a18);
  a29=(a29+a30);
  a29=(a16-a29);
  a29=(a29+a12);
  a30=(a3*a29);
  a30=(a4+a30);
  casadi_real a31=(a3*a20);
  a31=(a8+a31);
  casadi_real a32=(a7*a31);
  casadi_real a33=(a32+a32);
  casadi_real a34=(a3*a13);
  a34=(a0-a34);
  casadi_real a35=(a7*a34);
  a35=(a33*a35);
  a35=(a6*a35);
  a35=(a5*a35);
  a35=(a30*a35);
  a32=sq(a32);
  a32=(a6*a32);
  a32=(a32+a17);
  a32=(a32/a18);
  casadi_real a36=(a32*a27);
  a35=(a35-a36);
  a36=(a7*a31);
  casadi_real a37=(a36+a36);
  casadi_real a38=(a7*a34);
  a38=(a37*a38);
  a38=(a11*a38);
  a38=(a31*a38);
  a36=sq(a36);
  a36=(a11*a36);
  a36=(a36+a14);
  casadi_real a39=(a36*a34);
  a38=(a38+a39);
  a38=(a5*a38);
  a35=(a35+a38);
  a38=(a28*a35);
  a15=(a15+a38);
  a15=(a1*a15);
  a15=(a0-a15);
  a24=(a2*a24);
  a10=(a10+a24);
  a35=(a2*a35);
  a10=(a10+a35);
  a35=(a32*a30);
  a24=(a36*a31);
  a24=(a24/a18);
  a35=(a35+a24);
  a35=(a16-a35);
  a35=(a35+a12);
  a24=(a28*a35);
  a24=(a4+a24);
  a39=(a28*a30);
  a39=(a8+a39);
  casadi_real a40=(a7*a39);
  casadi_real a41=(a40+a40);
  casadi_real a42=(a28*a27);
  a42=(a0-a42);
  casadi_real a43=(a7*a42);
  a43=(a41*a43);
  a43=(a6*a43);
  a43=(a5*a43);
  a43=(a24*a43);
  a40=sq(a40);
  a40=(a6*a40);
  a40=(a40+a17);
  a40=(a40/a18);
  casadi_real a44=(a40*a38);
  a43=(a43-a44);
  a44=(a7*a39);
  casadi_real a45=(a44+a44);
  casadi_real a46=(a7*a42);
  a46=(a45*a46);
  a46=(a11*a46);
  a46=(a39*a46);
  a44=sq(a44);
  a44=(a11*a44);
  a44=(a44+a14);
  casadi_real a47=(a44*a42);
  a46=(a46+a47);
  a46=(a5*a46);
  a43=(a43+a46);
  a10=(a10+a43);
  a10=(a1*a10);
  a29=(a2*a29);
  a19=(a19+a29);
  a35=(a2*a35);
  a19=(a19+a35);
  a35=(a40*a24);
  a29=(a44*a39);
  a29=(a29/a18);
  a35=(a35+a29);
  a35=(a16-a35);
  a35=(a35+a12);
  a19=(a19+a35);
  a19=(a1*a19);
  a19=(a4+a19);
  a35=(a2*a20);
  a35=(a4+a35);
  a29=(a2*a30);
  a35=(a35+a29);
  a35=(a35+a24);
  a35=(a1*a35);
  a35=(a8+a35);
  a29=(a7*a35);
  a43=(a29+a29);
  a46=(a7*a15);
  a46=(a43*a46);
  a46=(a6*a46);
  a46=(a5*a46);
  a46=(a19*a46);
  a29=sq(a29);
  a29=(a6*a29);
  a29=(a29+a17);
  a29=(a29/a18);
  a47=(a29*a10);
  a46=(a46-a47);
  a47=(a7*a35);
  casadi_real a48=(a47+a47);
  casadi_real a49=(a7*a15);
  a49=(a48*a49);
  a49=(a11*a49);
  a49=(a35*a49);
  a47=sq(a47);
  a47=(a11*a47);
  a47=(a47+a14);
  casadi_real a50=(a47*a15);
  a49=(a49+a50);
  a49=(a5*a49);
  a46=(a46+a49);
  a49=(a3*a46);
  a49=(a10+a49);
  a50=(a2*a49);
  a50=(a10+a50);
  casadi_real a51=(a29*a19);
  casadi_real a52=(a47*a35);
  a52=(a52/a18);
  a51=(a51+a52);
  a51=(a16-a51);
  a51=(a51+a12);
  a51=(a3*a51);
  a51=(a19+a51);
  a52=(a3*a19);
  a52=(a35+a52);
  casadi_real a53=(a7*a52);
  casadi_real a54=(a53+a53);
  casadi_real a55=(a3*a10);
  a55=(a15-a55);
  casadi_real a56=(a7*a55);
  a56=(a54*a56);
  a56=(a6*a56);
  a56=(a5*a56);
  a56=(a51*a56);
  a53=sq(a53);
  a53=(a6*a53);
  a53=(a53+a17);
  a53=(a53/a18);
  casadi_real a57=(a53*a49);
  a56=(a56-a57);
  a57=(a7*a52);
  casadi_real a58=(a57+a57);
  casadi_real a59=(a7*a55);
  a59=(a58*a59);
  a59=(a11*a59);
  a59=(a52*a59);
  a57=sq(a57);
  a57=(a11*a57);
  a57=(a57+a14);
  casadi_real a60=(a57*a55);
  a59=(a59+a60);
  a59=(a5*a59);
  a56=(a56+a59);
  a59=(a3*a56);
  a59=(a10+a59);
  a60=(a2*a59);
  a50=(a50+a60);
  a60=(a53*a51);
  casadi_real a61=(a57*a52);
  a61=(a61/a18);
  a60=(a60+a61);
  a60=(a16-a60);
  a60=(a60+a12);
  a60=(a3*a60);
  a60=(a19+a60);
  a61=(a3*a51);
  a61=(a35+a61);
  casadi_real a62=(a7*a61);
  casadi_real a63=(a62+a62);
  casadi_real a64=(a3*a49);
  a64=(a15-a64);
  casadi_real a65=(a7*a64);
  a65=(a63*a65);
  a65=(a6*a65);
  a65=(a5*a65);
  a65=(a60*a65);
  a62=sq(a62);
  a62=(a6*a62);
  a62=(a62+a17);
  a62=(a62/a18);
  casadi_real a66=(a62*a59);
  a65=(a65-a66);
  a66=(a7*a61);
  casadi_real a67=(a66+a66);
  casadi_real a68=(a7*a64);
  a68=(a67*a68);
  a68=(a11*a68);
  a68=(a61*a68);
  a66=sq(a66);
  a66=(a11*a66);
  a66=(a66+a14);
  casadi_real a69=(a66*a64);
  a68=(a68+a69);
  a68=(a5*a68);
  a65=(a65+a68);
  a68=(a28*a65);
  a68=(a10+a68);
  a50=(a50+a68);
  a50=(a1*a50);
  a50=(a15-a50);
  if (res[0]!=0) res[0][0]=a50;
  a56=(a2*a56);
  a46=(a46+a56);
  a65=(a2*a65);
  a46=(a46+a65);
  a65=(a62*a60);
  a56=(a66*a61);
  a56=(a56/a18);
  a65=(a65+a56);
  a16=(a16-a65);
  a16=(a16+a12);
  a16=(a28*a16);
  a16=(a19+a16);
  a12=(a28*a60);
  a12=(a35+a12);
  a65=(a7*a12);
  a56=(a65+a65);
  a50=(a28*a59);
  a50=(a15-a50);
  a69=(a7*a50);
  a69=(a56*a69);
  a69=(a6*a69);
  a69=(a5*a69);
  a69=(a16*a69);
  a65=sq(a65);
  a65=(a6*a65);
  a65=(a65+a17);
  a65=(a65/a18);
  a18=(a65*a68);
  a69=(a69-a18);
  a18=(a7*a12);
  a17=(a18+a18);
  casadi_real a70=(a7*a50);
  a70=(a17*a70);
  a70=(a11*a70);
  a70=(a12*a70);
  a18=sq(a18);
  a18=(a11*a18);
  a18=(a18+a14);
  casadi_real a71=(a18*a50);
  a70=(a70+a71);
  a70=(a5*a70);
  a69=(a69+a70);
  a46=(a46+a69);
  a46=(a1*a46);
  a46=(a10+a46);
  a46=(-a46);
  if (res[0]!=0) res[0][1]=a46;
  a46=2400000.;
  a69=(a46*a4);
  a70=1200000.;
  a71=(a8+a8);
  a71=(a70*a71);
  a4=(a4*a71);
  a69=(a69+a4);
  a4=(a46*a20);
  a71=(a46*a21);
  casadi_real a72=(a71*a13);
  a4=(a4-a72);
  a72=(a21+a21);
  casadi_real a73=(a70*a72);
  a73=(a20*a73);
  casadi_real a74=sq(a21);
  a74=(a70*a74);
  a74=(a74+a14);
  a13=(a74*a13);
  a73=(a73-a13);
  a4=(a4+a73);
  a4=(a2*a4);
  a69=(a69+a4);
  a4=(a46*a34);
  a4=(a30*a4);
  a73=(a46*a31);
  a13=(a73*a27);
  a4=(a4-a13);
  a13=(a31+a31);
  a34=(a13*a34);
  a34=(a70*a34);
  a34=(a30*a34);
  casadi_real a75=sq(a31);
  a75=(a70*a75);
  a75=(a75+a14);
  a27=(a75*a27);
  a34=(a34-a27);
  a4=(a4+a34);
  a4=(a2*a4);
  a69=(a69+a4);
  a4=(a46*a42);
  a4=(a24*a4);
  a34=(a46*a39);
  a27=(a34*a38);
  a4=(a4-a27);
  a27=(a39+a39);
  a42=(a27*a42);
  a42=(a70*a42);
  a42=(a24*a42);
  casadi_real a76=sq(a39);
  a76=(a70*a76);
  a76=(a76+a14);
  a38=(a76*a38);
  a42=(a42-a38);
  a4=(a4+a42);
  a69=(a69+a4);
  a69=(a1*a69);
  a4=(a46*a15);
  a4=(a19*a4);
  a42=(a46*a35);
  a38=(a42*a10);
  a4=(a4-a38);
  a38=(a35+a35);
  a15=(a38*a15);
  a15=(a70*a15);
  a15=(a19*a15);
  casadi_real a77=sq(a35);
  a77=(a70*a77);
  a77=(a77+a14);
  a10=(a77*a10);
  a15=(a15-a10);
  a4=(a4+a15);
  a15=(a46*a55);
  a15=(a51*a15);
  a10=(a46*a52);
  casadi_real a78=(a10*a49);
  a15=(a15-a78);
  a78=(a52+a52);
  a55=(a78*a55);
  a55=(a70*a55);
  a55=(a51*a55);
  casadi_real a79=sq(a52);
  a79=(a70*a79);
  a79=(a79+a14);
  a49=(a79*a49);
  a55=(a55-a49);
  a15=(a15+a55);
  a15=(a2*a15);
  a4=(a4+a15);
  a15=(a46*a64);
  a15=(a60*a15);
  a55=(a46*a61);
  a49=(a55*a59);
  a15=(a15-a49);
  a49=(a61+a61);
  a64=(a49*a64);
  a64=(a70*a64);
  a64=(a60*a64);
  casadi_real a80=sq(a61);
  a80=(a70*a80);
  a80=(a80+a14);
  a59=(a80*a59);
  a64=(a64-a59);
  a15=(a15+a64);
  a15=(a2*a15);
  a4=(a4+a15);
  a15=(a46*a50);
  a15=(a16*a15);
  a64=(a46*a12);
  a59=(a64*a68);
  a15=(a15-a59);
  a59=(a12+a12);
  a50=(a59*a50);
  a50=(a70*a50);
  a50=(a16*a50);
  casadi_real a81=sq(a12);
  a81=(a70*a81);
  a81=(a81+a14);
  a68=(a81*a68);
  a50=(a50-a68);
  a15=(a15+a50);
  a4=(a4+a15);
  a4=(a1*a4);
  a69=(a69+a4);
  if (res[0]!=0) res[0][2]=a69;
  a69=0.;
  if (res[0]!=0) res[0][3]=a69;
  a4=(a3*a9);
  a4=(a0-a4);
  a15=(a2*a4);
  a15=(a0+a15);
  a50=1.2500000000000001e-002;
  a23=(a50*a23);
  a23=(a6*a23);
  a23=(a5*a23);
  a23=(a20*a23);
  a22=(a22*a4);
  a23=(a23+a22);
  a50=(a50*a26);
  a50=(a11*a50);
  a21=(a21*a50);
  a25=(a3*a25);
  a21=(a21+a25);
  a21=(a5*a21);
  a23=(a23+a21);
  a21=(a3*a23);
  a21=(a0-a21);
  a25=(a2*a21);
  a15=(a15+a25);
  a25=(a3*a4);
  a50=(a7*a25);
  a33=(a33*a50);
  a33=(a6*a33);
  a33=(a5*a33);
  a33=(a30*a33);
  a32=(a32*a21);
  a33=(a33+a32);
  a32=(a7*a25);
  a37=(a37*a32);
  a37=(a11*a37);
  a31=(a31*a37);
  a36=(a36*a25);
  a31=(a31+a36);
  a31=(a5*a31);
  a33=(a33+a31);
  a31=(a28*a33);
  a31=(a0-a31);
  a15=(a15+a31);
  a15=(a1*a15);
  a23=(a2*a23);
  a9=(a9+a23);
  a33=(a2*a33);
  a9=(a9+a33);
  a33=(a28*a21);
  a23=(a7*a33);
  a41=(a41*a23);
  a41=(a6*a41);
  a41=(a5*a41);
  a41=(a24*a41);
  a40=(a40*a31);
  a41=(a41+a40);
  a40=(a7*a33);
  a45=(a45*a40);
  a45=(a11*a45);
  a39=(a39*a45);
  a44=(a44*a33);
  a39=(a39+a44);
  a39=(a5*a39);
  a41=(a41+a39);
  a9=(a9+a41);
  a9=(a1*a9);
  a9=(a0-a9);
  a41=(a7*a15);
  a43=(a43*a41);
  a43=(a6*a43);
  a43=(a5*a43);
  a43=(a19*a43);
  a29=(a29*a9);
  a43=(a43+a29);
  a29=(a7*a15);
  a48=(a48*a29);
  a48=(a11*a48);
  a35=(a35*a48);
  a47=(a47*a15);
  a35=(a35+a47);
  a35=(a5*a35);
  a43=(a43+a35);
  a35=(a3*a43);
  a35=(a9-a35);
  a47=(a2*a35);
  a47=(a9+a47);
  a48=(a3*a9);
  a48=(a15+a48);
  a29=(a7*a48);
  a54=(a54*a29);
  a54=(a6*a54);
  a54=(a5*a54);
  a54=(a51*a54);
  a53=(a53*a35);
  a54=(a54+a53);
  a53=(a7*a48);
  a58=(a58*a53);
  a58=(a11*a58);
  a52=(a52*a58);
  a57=(a57*a48);
  a52=(a52+a57);
  a52=(a5*a52);
  a54=(a54+a52);
  a52=(a3*a54);
  a52=(a9-a52);
  a57=(a2*a52);
  a47=(a47+a57);
  a57=(a3*a35);
  a57=(a15+a57);
  a58=(a7*a57);
  a63=(a63*a58);
  a63=(a6*a63);
  a63=(a5*a63);
  a63=(a60*a63);
  a62=(a62*a52);
  a63=(a63+a62);
  a62=(a7*a57);
  a67=(a67*a62);
  a67=(a11*a67);
  a61=(a61*a67);
  a66=(a66*a57);
  a61=(a61+a66);
  a61=(a5*a61);
  a63=(a63+a61);
  a61=(a28*a63);
  a61=(a9-a61);
  a47=(a47+a61);
  a47=(a1*a47);
  a47=(a15+a47);
  if (res[0]!=0) res[0][4]=a47;
  a54=(a2*a54);
  a43=(a43+a54);
  a63=(a2*a63);
  a43=(a43+a63);
  a28=(a28*a52);
  a28=(a15+a28);
  a63=(a7*a28);
  a56=(a56*a63);
  a6=(a6*a56);
  a6=(a5*a6);
  a6=(a16*a6);
  a65=(a65*a61);
  a6=(a6+a65);
  a7=(a7*a28);
  a17=(a17*a7);
  a11=(a11*a17);
  a12=(a12*a11);
  a18=(a18*a28);
  a12=(a12+a18);
  a5=(a5*a12);
  a6=(a6+a5);
  a43=(a43+a6);
  a43=(a1*a43);
  a43=(a9-a43);
  if (res[0]!=0) res[0][5]=a43;
  a43=(a46*a8);
  a8=sq(a8);
  a8=(a70*a8);
  a8=(a8+a14);
  a43=(a43+a8);
  a8=3000.;
  a8=(a8*a20);
  a71=(a71*a4);
  a8=(a8+a71);
  a3=(a3*a72);
  a3=(a70*a3);
  a20=(a20*a3);
  a74=(a74*a4);
  a20=(a20+a74);
  a8=(a8+a20);
  a8=(a2*a8);
  a43=(a43+a8);
  a8=(a46*a25);
  a8=(a30*a8);
  a73=(a73*a21);
  a8=(a8+a73);
  a13=(a13*a25);
  a13=(a70*a13);
  a30=(a30*a13);
  a75=(a75*a21);
  a30=(a30+a75);
  a8=(a8+a30);
  a8=(a2*a8);
  a43=(a43+a8);
  a8=(a46*a33);
  a8=(a24*a8);
  a34=(a34*a31);
  a8=(a8+a34);
  a27=(a27*a33);
  a27=(a70*a27);
  a24=(a24*a27);
  a76=(a76*a31);
  a24=(a24+a76);
  a8=(a8+a24);
  a43=(a43+a8);
  a43=(a1*a43);
  a8=(a46*a15);
  a8=(a19*a8);
  a42=(a42*a9);
  a8=(a8+a42);
  a38=(a38*a15);
  a38=(a70*a38);
  a19=(a19*a38);
  a77=(a77*a9);
  a19=(a19+a77);
  a8=(a8+a19);
  a19=(a46*a48);
  a19=(a51*a19);
  a10=(a10*a35);
  a19=(a19+a10);
  a78=(a78*a48);
  a78=(a70*a78);
  a51=(a51*a78);
  a79=(a79*a35);
  a51=(a51+a79);
  a19=(a19+a51);
  a19=(a2*a19);
  a8=(a8+a19);
  a19=(a46*a57);
  a19=(a60*a19);
  a55=(a55*a52);
  a19=(a19+a55);
  a49=(a49*a57);
  a49=(a70*a49);
  a60=(a60*a49);
  a80=(a80*a52);
  a60=(a60+a80);
  a19=(a19+a60);
  a2=(a2*a19);
  a8=(a8+a2);
  a46=(a46*a28);
  a46=(a16*a46);
  a64=(a64*a61);
  a46=(a46+a64);
  a59=(a59*a28);
  a70=(a70*a59);
  a16=(a16*a70);
  a81=(a81*a61);
  a16=(a16+a81);
  a46=(a46+a16);
  a8=(a8+a46);
  a1=(a1*a8);
  a43=(a43+a1);
  if (res[0]!=0) res[0][6]=a43;
  if (res[0]!=0) res[0][7]=a69;
  if (res[0]!=0) res[0][8]=a69;
  if (res[0]!=0) res[0][9]=a69;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a69;
  if (res[0]!=0) res[0][12]=a69;
  if (res[0]!=0) res[0][13]=a69;
  if (res[0]!=0) res[0][14]=a69;
  if (res[0]!=0) res[0][15]=a0;
  if (res[1]!=0) res[1][0]=a69;
  if (res[1]!=0) res[1][1]=a69;
  a69=5.0000000000000001e-003;
  if (res[1]!=0) res[1][2]=a69;
  if (res[1]!=0) res[1][3]=a69;
  return 0;
}

CASADI_SYMBOL_EXPORT int D(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void D_incref(void) {
}

CASADI_SYMBOL_EXPORT void D_decref(void) {
}

CASADI_SYMBOL_EXPORT int D_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int D_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* D_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* D_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* D_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* D_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int D_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 82;
  return 0;
}

/* h_fun:(states[4],controls,params[3])->(h[2]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int h_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* h_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_fun_name_out(int i){
  switch (i) {
    case 0: return "h";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* h_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* h_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int h_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* path_con_fun:(states[4],controls,params[3])->(path_con[]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int path_con_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_out(int i){
  switch (i) {
    case 0: return "path_con";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* path_con_N_fun:(states[4],params[3])->(path_con_N[]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_out(int i){
  switch (i) {
    case 0: return "path_con_N";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obji_fun:(i0[4],i1,i2[3],i3[2],i4[2x2])->(o0) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[4] ? arg[4][0] : 0;
  a1=sqrt(a1);
  casadi_real a2=arg[0] ? arg[0][2] : 0;
  casadi_real a3=arg[3] ? arg[3][0] : 0;
  a2=(a2-a3);
  a1=(a1*a2);
  a3=arg[4] ? arg[4][2] : 0;
  a3=sqrt(a3);
  casadi_real a4=arg[0] ? arg[0][3] : 0;
  casadi_real a5=arg[3] ? arg[3][1] : 0;
  a4=(a4-a5);
  a3=(a3*a4);
  a1=(a1+a3);
  a1=sq(a1);
  a3=arg[4] ? arg[4][1] : 0;
  a3=sqrt(a3);
  a3=(a3*a2);
  a2=arg[4] ? arg[4][3] : 0;
  a2=sqrt(a2);
  a2=(a2*a4);
  a3=(a3+a2);
  a3=sq(a3);
  a1=(a1+a3);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void obji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void obji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int obji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int obji_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obji_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obji_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obji_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}

/* objN_fun:(i0[4],i1[3],i2,i3)->(o0) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[3] ? arg[3][0] : 0;
  a1=sqrt(a1);
  casadi_real a2=arg[0] ? arg[0][3] : 0;
  casadi_real a3=arg[2] ? arg[2][0] : 0;
  a2=(a2-a3);
  a1=(a1*a2);
  a1=fabs(a1);
  a1=sq(a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void objN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void objN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int objN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int objN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* objN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* objN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int objN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* gi_fun:(i0[4],i1,i2[3],i3[2],i4[2x2])->(o0[4],o1) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[4] ? arg[4][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][2] : 0;
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3-a4);
  a4=(a2*a3);
  casadi_real a5=arg[4] ? arg[4][2] : 0;
  a5=sqrt(a5);
  casadi_real a6=arg[0] ? arg[0][3] : 0;
  casadi_real a7=arg[3] ? arg[3][1] : 0;
  a6=(a6-a7);
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a4+a4);
  a2=(a4*a2);
  a7=arg[4] ? arg[4][1] : 0;
  a7=sqrt(a7);
  a3=(a7*a3);
  casadi_real a8=arg[4] ? arg[4][3] : 0;
  a8=sqrt(a8);
  a6=(a8*a6);
  a3=(a3+a6);
  a3=(a3+a3);
  a7=(a3*a7);
  a2=(a2+a7);
  a2=(a1*a2);
  if (res[0]!=0) res[0][2]=a2;
  a4=(a4*a5);
  a3=(a3*a8);
  a4=(a4+a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][3]=a1;
  if (res[1]!=0) res[1][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int gi_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gi_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gi_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gi_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 9;
  return 0;
}

/* gN_fun:(i0[4],i1[3],i2,i3)->(o0[4]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=5.0000000000000000e-001;
  casadi_real a1=arg[3] ? arg[3][0] : 0;
  a1=sqrt(a1);
  casadi_real a2=arg[0] ? arg[0][3] : 0;
  casadi_real a3=arg[2] ? arg[2][0] : 0;
  a2=(a2-a3);
  a2=(a1*a2);
  a3=fabs(a2);
  a3=(a3+a3);
  a2=sign(a2);
  a2=(a2*a1);
  a3=(a3*a2);
  a0=(a0*a3);
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int gN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* Ji_fun:(i0[4],i1,i2[3],i3[2],i4[2x2])->(o0[2x4],o1[2]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  casadi_real a1=arg[4] ? arg[4][0] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[4] ? arg[4][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[4] ? arg[4][2] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][6]=a1;
  a1=arg[4] ? arg[4][3] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][7]=a1;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Ji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Ji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int Ji_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ji_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ji_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ji_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* JN_fun:(i0[4],i1[3],i2,i3)->(o0[1x4]) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3] ? arg[3][0] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f16(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void JN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void JN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int JN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int JN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* JN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* JN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int JN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* Ci_fun:(i0[4],i1,i2[3])->(o0[0x4],o1[0]) */
static int casadi_f17(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f17(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Ci_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ci_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Ci_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int Ci_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ci_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ci_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ci_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* CN_fun:(i0[4],i1[3])->(o0[0x4]) */
static int casadi_f18(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f18(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void CN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void CN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int CN_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int CN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* CN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* CN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int CN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* adj_fun:(i0[4],i1,i2[3],i3[2],i4[2x2],i5[4],i6[0])->(o0[5],o1[5],o2[5]) */
static int casadi_f19(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[4] ? arg[4][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][2] : 0;
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3-a4);
  a4=(a2*a3);
  casadi_real a5=arg[4] ? arg[4][2] : 0;
  a5=sqrt(a5);
  casadi_real a6=arg[0] ? arg[0][3] : 0;
  casadi_real a7=arg[3] ? arg[3][1] : 0;
  a6=(a6-a7);
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a4+a4);
  a2=(a4*a2);
  a7=arg[4] ? arg[4][1] : 0;
  a7=sqrt(a7);
  a3=(a7*a3);
  casadi_real a8=arg[4] ? arg[4][3] : 0;
  a8=sqrt(a8);
  a6=(a8*a6);
  a3=(a3+a6);
  a3=(a3+a3);
  a7=(a3*a7);
  a2=(a2+a7);
  a2=(a1*a2);
  if (res[0]!=0) res[0][2]=a2;
  a4=(a4*a5);
  a3=(a3*a8);
  a4=(a4+a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  a1=arg[0] ? arg[0][0] : 0;
  a4=(a1+a1);
  a3=1200000.;
  a8=arg[0] ? arg[0][1] : 0;
  a5=4.1666666666666669e-004;
  a2=arg[5] ? arg[5][2] : 0;
  a7=(a5*a2);
  a6=(a8*a7);
  a6=(a3*a6);
  a4=(a4*a6);
  a6=2400000.;
  casadi_real a9=(a8*a7);
  a9=(a6*a9);
  a4=(a4+a9);
  a9=2.5000000000000001e-003;
  casadi_real a10=1.2500000000000000e-003;
  casadi_real a11=arg[2] ? arg[2][2] : 0;
  casadi_real a12=200.;
  casadi_real a13=10.;
  casadi_real a14=(a10*a8);
  a14=(a1+a14);
  casadi_real a15=(a13*a14);
  casadi_real a16=sq(a15);
  a16=(a12*a16);
  casadi_real a17=2000.;
  a16=(a16+a17);
  casadi_real a18=67.;
  a16=(a16/a18);
  casadi_real a19=(a13*a1);
  casadi_real a20=sq(a19);
  a20=(a12*a20);
  a20=(a20+a17);
  a20=(a20/a18);
  casadi_real a21=(a20*a8);
  casadi_real a22=12000.;
  casadi_real a23=(a13*a1);
  casadi_real a24=sq(a23);
  a24=(a22*a24);
  casadi_real a25=1000.;
  a24=(a24+a25);
  casadi_real a26=(a24*a1);
  a26=(a26/a18);
  a21=(a21+a26);
  a21=(a11-a21);
  a26=9.8100000000000005e+000;
  casadi_real a27=arg[2] ? arg[2][1] : 0;
  a26=(a26*a27);
  a21=(a21+a26);
  a27=(a10*a21);
  a27=(a8+a27);
  casadi_real a28=(a16*a27);
  casadi_real a29=(a13*a14);
  casadi_real a30=sq(a29);
  a30=(a22*a30);
  a30=(a30+a25);
  casadi_real a31=(a30*a14);
  a31=(a31/a18);
  a28=(a28+a31);
  a28=(a11-a28);
  a28=(a28+a26);
  a31=(a10*a28);
  a31=(a8+a31);
  casadi_real a32=(a9*a31);
  a32=(a1+a32);
  casadi_real a33=(a32+a32);
  casadi_real a34=(a10*a27);
  a34=(a1+a34);
  casadi_real a35=(a13*a34);
  casadi_real a36=sq(a35);
  a36=(a12*a36);
  a36=(a36+a17);
  a36=(a36/a18);
  casadi_real a37=(a36*a31);
  casadi_real a38=(a13*a34);
  casadi_real a39=sq(a38);
  a39=(a22*a39);
  a39=(a39+a25);
  casadi_real a40=(a39*a34);
  a40=(a40/a18);
  a37=(a37+a40);
  a37=(a11-a37);
  a37=(a37+a26);
  a40=(a9*a37);
  a40=(a8+a40);
  casadi_real a41=(a40*a7);
  a41=(a3*a41);
  a33=(a33*a41);
  a41=(a40*a7);
  a41=(a6*a41);
  a33=(a33+a41);
  a41=(a13*a32);
  casadi_real a42=sq(a41);
  a42=(a22*a42);
  a42=(a42+a25);
  casadi_real a43=1.4925373134328358e-002;
  casadi_real a44=2.;
  casadi_real a45=(a44*a27);
  a45=(a8+a45);
  casadi_real a46=(a44*a31);
  a45=(a45+a46);
  a45=(a45+a40);
  a45=(a5*a45);
  a45=(a1+a45);
  a46=sq(a45);
  a46=(a3*a46);
  a46=(a46+a25);
  casadi_real a47=(a5*a2);
  a46=(a46*a47);
  casadi_real a48=(a6*a45);
  a48=(a48*a47);
  a46=(a46+a48);
  a48=arg[5] ? arg[5][1] : 0;
  a46=(a46+a48);
  a28=(a44*a28);
  a21=(a21+a28);
  a37=(a44*a37);
  a21=(a21+a37);
  a37=(a13*a32);
  a28=sq(a37);
  a28=(a12*a28);
  a28=(a28+a17);
  a28=(a28/a18);
  casadi_real a49=(a28*a40);
  casadi_real a50=(a42*a32);
  a50=(a50/a18);
  a49=(a49+a50);
  a49=(a11-a49);
  a49=(a49+a26);
  a21=(a21+a49);
  a21=(a5*a21);
  a21=(a8+a21);
  a49=(a10*a21);
  a49=(a45+a49);
  a50=(a13*a49);
  casadi_real a51=sq(a50);
  a51=(a12*a51);
  a51=(a51+a17);
  a51=(a51/a18);
  casadi_real a52=(a13*a45);
  casadi_real a53=sq(a52);
  a53=(a12*a53);
  a53=(a53+a17);
  a53=(a53/a18);
  casadi_real a54=(a53*a21);
  casadi_real a55=(a13*a45);
  casadi_real a56=sq(a55);
  a56=(a22*a56);
  a56=(a56+a25);
  casadi_real a57=(a56*a45);
  a57=(a57/a18);
  a54=(a54+a57);
  a54=(a11-a54);
  a54=(a54+a26);
  a54=(a10*a54);
  a54=(a21+a54);
  a57=(a51*a54);
  casadi_real a58=(a13*a49);
  casadi_real a59=sq(a58);
  a59=(a22*a59);
  a59=(a59+a25);
  casadi_real a60=(a59*a49);
  a60=(a60/a18);
  a57=(a57+a60);
  a57=(a11-a57);
  a57=(a57+a26);
  a57=(a10*a57);
  a57=(a21+a57);
  a60=(a9*a57);
  a60=(a45+a60);
  casadi_real a61=sq(a60);
  a61=(a3*a61);
  a61=(a61+a25);
  a61=(a61*a47);
  casadi_real a62=(a6*a60);
  a62=(a62*a47);
  a61=(a61+a62);
  a62=(a13*a60);
  casadi_real a63=sq(a62);
  a63=(a12*a63);
  a63=(a63+a17);
  a63=(a63/a18);
  a48=(a5*a48);
  a63=(a63*a48);
  a61=(a61-a63);
  a63=arg[5] ? arg[5][0] : 0;
  casadi_real a64=(a5*a63);
  a61=(a61+a64);
  a46=(a46+a61);
  casadi_real a65=(a10*a54);
  a65=(a45+a65);
  casadi_real a66=sq(a65);
  a66=(a3*a66);
  a66=(a66+a25);
  casadi_real a67=(a44*a47);
  a66=(a66*a67);
  casadi_real a68=(a6*a65);
  a68=(a68*a67);
  a66=(a66+a68);
  a68=(a60+a60);
  casadi_real a69=(a13*a65);
  casadi_real a70=sq(a69);
  a70=(a12*a70);
  a70=(a70+a17);
  a70=(a70/a18);
  a17=(a70*a57);
  casadi_real a71=(a13*a65);
  casadi_real a72=sq(a71);
  a72=(a22*a72);
  a72=(a72+a25);
  casadi_real a73=(a72*a65);
  a73=(a73/a18);
  a17=(a17+a73);
  a11=(a11-a17);
  a11=(a11+a26);
  a11=(a9*a11);
  a11=(a21+a11);
  a26=(a11*a47);
  a26=(a3*a26);
  a68=(a68*a26);
  a26=(a11*a47);
  a26=(a6*a26);
  a68=(a68+a26);
  a26=(a13*a60);
  a17=sq(a26);
  a17=(a22*a17);
  a17=(a17+a25);
  a73=(a43*a48);
  a17=(a17*a73);
  a68=(a68-a17);
  a26=(a26+a26);
  a60=(a60*a73);
  a60=(a22*a60);
  a26=(a26*a60);
  a26=(a13*a26);
  a68=(a68-a26);
  a62=(a62+a62);
  a11=(a11*a48);
  a11=(a43*a11);
  a11=(a12*a11);
  a62=(a62*a11);
  a62=(a13*a62);
  a68=(a68-a62);
  a62=(a9*a68);
  a66=(a66+a62);
  a62=(a44*a48);
  a61=(a9*a61);
  a62=(a62+a61);
  a70=(a70*a62);
  a66=(a66-a70);
  a70=(a44*a64);
  a66=(a66+a70);
  a46=(a46+a66);
  a70=(a49+a49);
  a61=(a44*a47);
  a11=(a54*a61);
  a11=(a3*a11);
  a70=(a70*a11);
  a11=(a54*a61);
  a11=(a6*a11);
  a70=(a70+a11);
  a11=(a44*a48);
  a66=(a10*a66);
  a11=(a11+a66);
  a66=(a43*a11);
  a59=(a59*a66);
  a70=(a70-a59);
  a58=(a58+a58);
  a66=(a49*a66);
  a66=(a22*a66);
  a58=(a58*a66);
  a58=(a13*a58);
  a70=(a70-a58);
  a50=(a50+a50);
  a54=(a54*a11);
  a54=(a43*a54);
  a54=(a12*a54);
  a50=(a50*a54);
  a50=(a13*a50);
  a70=(a70-a50);
  a50=(a10*a70);
  a46=(a46+a50);
  a46=(a46+a64);
  a50=sq(a49);
  a50=(a3*a50);
  a50=(a50+a25);
  a50=(a50*a61);
  a49=(a6*a49);
  a49=(a49*a61);
  a50=(a50+a49);
  a49=(a65+a65);
  a54=(a57*a67);
  a54=(a3*a54);
  a49=(a49*a54);
  a54=(a57*a67);
  a54=(a6*a54);
  a49=(a49+a54);
  a54=(a43*a62);
  a72=(a72*a54);
  a49=(a49-a72);
  a71=(a71+a71);
  a65=(a65*a54);
  a65=(a22*a65);
  a71=(a71*a65);
  a71=(a13*a71);
  a49=(a49-a71);
  a69=(a69+a69);
  a57=(a57*a62);
  a57=(a43*a57);
  a57=(a12*a57);
  a69=(a69*a57);
  a69=(a13*a69);
  a49=(a49-a69);
  a69=(a10*a49);
  a50=(a50+a69);
  a51=(a51*a11);
  a50=(a50-a51);
  a64=(a44*a64);
  a50=(a50+a64);
  a46=(a46+a50);
  a50=(a10*a50);
  a48=(a48+a50);
  a53=(a53*a48);
  a46=(a46-a53);
  a53=(a5*a46);
  a50=(a43*a53);
  a42=(a42*a50);
  a33=(a33-a42);
  a41=(a41+a41);
  a50=(a32*a50);
  a50=(a22*a50);
  a41=(a41*a50);
  a41=(a13*a41);
  a33=(a33-a41);
  a37=(a37+a37);
  a40=(a40*a53);
  a40=(a43*a40);
  a40=(a12*a40);
  a37=(a37*a40);
  a37=(a13*a37);
  a33=(a33-a37);
  a4=(a4+a33);
  a37=(a45+a45);
  a40=(a21*a47);
  a40=(a3*a40);
  a37=(a37*a40);
  a40=(a21*a47);
  a40=(a6*a40);
  a37=(a37+a40);
  a37=(a37+a68);
  a37=(a37+a63);
  a37=(a37+a49);
  a37=(a37+a70);
  a70=(a43*a48);
  a56=(a56*a70);
  a37=(a37-a56);
  a55=(a55+a55);
  a45=(a45*a70);
  a45=(a22*a45);
  a55=(a55*a45);
  a55=(a13*a55);
  a37=(a37-a55);
  a52=(a52+a52);
  a21=(a21*a48);
  a21=(a43*a21);
  a21=(a12*a21);
  a52=(a52*a21);
  a52=(a13*a52);
  a37=(a37-a52);
  a4=(a4+a37);
  a52=(a34+a34);
  a21=(a44*a7);
  a48=(a31*a21);
  a48=(a3*a48);
  a52=(a52*a48);
  a48=(a31*a21);
  a48=(a6*a48);
  a52=(a52+a48);
  a48=(a44*a53);
  a55=sq(a32);
  a55=(a3*a55);
  a55=(a55+a25);
  a55=(a55*a7);
  a32=(a6*a32);
  a32=(a32*a7);
  a55=(a55+a32);
  a28=(a28*a53);
  a55=(a55-a28);
  a37=(a5*a37);
  a55=(a55+a37);
  a28=(a9*a55);
  a48=(a48+a28);
  a28=(a43*a48);
  a39=(a39*a28);
  a52=(a52-a39);
  a38=(a38+a38);
  a28=(a34*a28);
  a28=(a22*a28);
  a38=(a38*a28);
  a38=(a13*a38);
  a52=(a52-a38);
  a35=(a35+a35);
  a31=(a31*a48);
  a31=(a43*a31);
  a31=(a12*a31);
  a35=(a35*a31);
  a35=(a13*a35);
  a52=(a52-a35);
  a4=(a4+a52);
  a35=(a14+a14);
  a31=(a44*a7);
  a38=(a27*a31);
  a38=(a3*a38);
  a35=(a35*a38);
  a38=(a27*a31);
  a38=(a6*a38);
  a35=(a35+a38);
  a38=(a44*a53);
  a28=sq(a34);
  a28=(a3*a28);
  a28=(a28+a25);
  a28=(a28*a21);
  a34=(a6*a34);
  a34=(a34*a21);
  a28=(a28+a34);
  a9=(a9*a33);
  a28=(a28+a9);
  a36=(a36*a48);
  a28=(a28-a36);
  a36=(a44*a37);
  a28=(a28+a36);
  a36=(a10*a28);
  a38=(a38+a36);
  a36=(a43*a38);
  a30=(a30*a36);
  a35=(a35-a30);
  a29=(a29+a29);
  a36=(a14*a36);
  a36=(a22*a36);
  a29=(a29*a36);
  a29=(a13*a29);
  a35=(a35-a29);
  a15=(a15+a15);
  a27=(a27*a38);
  a27=(a43*a27);
  a27=(a12*a27);
  a15=(a15*a27);
  a15=(a13*a15);
  a35=(a35-a15);
  a4=(a4+a35);
  a15=sq(a14);
  a15=(a3*a15);
  a15=(a15+a25);
  a15=(a15*a31);
  a14=(a6*a14);
  a14=(a14*a31);
  a15=(a15+a14);
  a52=(a10*a52);
  a15=(a15+a52);
  a16=(a16*a38);
  a15=(a15-a16);
  a16=(a44*a37);
  a15=(a15+a16);
  a16=(a10*a15);
  a53=(a53+a16);
  a16=(a43*a53);
  a24=(a24*a16);
  a4=(a4-a24);
  a23=(a23+a23);
  a16=(a1*a16);
  a22=(a22*a16);
  a23=(a23*a22);
  a23=(a13*a23);
  a4=(a4-a23);
  a19=(a19+a19);
  a8=(a8*a53);
  a43=(a43*a8);
  a12=(a12*a43);
  a19=(a19*a12);
  a13=(a13*a19);
  a4=(a4-a13);
  if (res[1]!=0) res[1][0]=a4;
  a4=sq(a1);
  a3=(a3*a4);
  a3=(a3+a25);
  a3=(a3*a7);
  a6=(a6*a1);
  a6=(a6*a7);
  a3=(a3+a6);
  a3=(a3+a46);
  a3=(a3+a55);
  a3=(a3+a28);
  a10=(a10*a35);
  a3=(a3+a10);
  a3=(a3+a37);
  a3=(a3+a15);
  a20=(a20*a53);
  a3=(a3-a20);
  if (res[1]!=0) res[1][1]=a3;
  if (res[1]!=0) res[1][2]=a2;
  a2=arg[5] ? arg[5][3] : 0;
  if (res[1]!=0) res[1][3]=a2;
  a3=(a5*a2);
  a20=(a44*a3);
  a20=(a3+a20);
  a20=(a20+a3);
  a3=(a44*a3);
  a20=(a20+a3);
  a5=(a5*a2);
  a20=(a20+a5);
  a2=(a44*a5);
  a20=(a20+a2);
  a20=(a20+a5);
  a44=(a44*a5);
  a20=(a20+a44);
  a20=(a20+a47);
  a20=(a20+a67);
  a20=(a20+a61);
  a20=(a20+a47);
  a20=(a20+a7);
  a20=(a20+a21);
  a20=(a20+a31);
  a20=(a20+a7);
  if (res[1]!=0) res[1][4]=a20;
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  if (res[2]!=0) res[2][3]=a0;
  if (res[2]!=0) res[2][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f19(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adj_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adj_fun_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT int adj_fun_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    case 5: return casadi_s0;
    case 6: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s11;
    case 2: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 74;
  return 0;
}

/* adjN_fun:(i0[4],i1[3],i2,i3,i4[0])->(o0[4],o1[4]) */
static int casadi_f20(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[3] ? arg[3][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][3] : 0;
  casadi_real a4=arg[2] ? arg[2][0] : 0;
  a3=(a3-a4);
  a3=(a2*a3);
  a4=fabs(a3);
  a4=(a4+a4);
  a3=sign(a3);
  a3=(a3*a2);
  a4=(a4*a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][3]=a1;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f20(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adjN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adjN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adjN_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int adjN_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adjN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
